/**
 * @file MapNexusCore.c
 * @brief Implementation of the three-phase EFI->kernel map. Rationale lives in MapNexusCore.h.
 */

#include "MapNexusCore.h"
#include "NexusBootDxe.h"
#include "Sha256.h"
#include <Library/BaseMemoryLib.h>   /* CopyMem / ZeroMem / CompareMem */
#include <Library/BaseLib.h>        /* AsmReadTsc                     */

/*
 * CR8 read via the MSVC INTRINSIC, deliberately not BaseLib's AsmReadCr8().
 *
 * AsmReadCr8 is DECLARED in BaseLib.h but is not present in the EDK2 library we link -- it fails at
 * LINK with LNK2001, not at compile, so the declaration reads as availability. (AsmReadTsc above
 * does link, so this is missing per-function, not a missing library.) Same shape as the support-lib
 * trim trap: "declared" is not "implemented".
 *
 * The intrinsic compiles to a single `mov rax, cr8` with no library dependency at all, which is
 * strictly better here -- this runs from a runtime-services hook where we want zero external calls.
 */
unsigned __int64 __readcr8(void);
#pragma intrinsic(__readcr8)
#include "../Include/PeRelocate.h"
#include "../../Include/NexusCoreBoot.h"
/*
 * Included WITHOUT NXC_NT_API_TYPED: the typed half needs NTSTATUS/KIRQL/PVOID which do not exist
 * here. We want only the untyped half -- the export name, magic, slot layout and the name list in
 * field order -- so the pointers we write land in the same order the payload's struct declares.
 */
#include "../../Include/NexusNtApi.h"

/* Generated by tools/embed_driver.py. Defines NXC_PAYLOAD_* and NxcPayloadBytes/NxcPayloadSha256. */
#include "NexusCorePayload.h"

/*
 * ---------------------------------------------------------------------------------------------
 * State. Deliberately file-static rather than in gKernelPatchInfo: that buffer is EfiGuard's
 * message log and stuffing unrelated pointers into it invites exactly the kind of layout coupling
 * that has already cost this project a shipped bug. These are plain globals in the DXE image,
 * which is itself relocated coherently, so they stay valid across both winload contexts for the
 * same reason gKernelPatchInfo does.
 * ---------------------------------------------------------------------------------------------
 */
STATIC UINT8*                  mImageBase       = NULL;   /* mapped NexusCore, SizeOfImage bytes  */
STATIC UINTN                   mImageSize       = 0;
STATIC NEXUS_CORE_BOOT_BLOCK*  mBootBlock       = NULL;   /* lives in the same reservation        */
STATIC BOOLEAN                 mStaged          = FALSE;  /* phase 1 completed                    */
STATIC BOOLEAN                 mBound           = FALSE;  /* phase 2 completed                    */
STATIC BOOLEAN                 mVirtualRelocated = FALSE; /* phase 3 one-shot -- twice is fatal   */
STATIC BOOLEAN                 mArmed           = FALSE;  /* phase 4 may fire (set by phase 3)    */
STATIC BOOLEAN                 mLaunched        = FALSE;  /* phase 4 one-shot                     */
STATIC UINT32                  mLaunchCalls     = 0;      /* hooked calls seen while armed        */
STATIC UINT32                  mRejectedIrql    = 0;      /* CR8 gate rejections                  */
STATIC UINT32                  mBootSlotRva     = 0;      /* payload's exported NexusCoreBootSlot */
STATIC VOID**                  mHijackField     = NULL;   /* &KldrEntry->EntryPoint of the target  */
STATIC VOID*                   mHijackOriginal  = NULL;   /* its original value, for the proxy     */

/* Where the boot block sits inside the reservation: immediately after the image, page-aligned. */
#define NXC_BLOCK_OFFSET  ALIGN_VALUE(NXC_PAYLOAD_SIZE_OF_IMAGE, EFI_PAGE_SIZE)
#define NXC_TOTAL_BYTES   (NXC_BLOCK_OFFSET + EFI_PAGE_SIZE)

/*
 * RUNTIME MAP ARENA SIZE. Reserved once, here, because gBS is unavailable by the time NexusCore
 * wants to map anything -- see the long note on ArenaBase in NexusCoreBoot.h.
 *
 * 16 MB is sized for the real workload: the driver that will be mapped/unmapped/remapped most is the
 * HYPERVISOR, which needs room for VMCS regions, EPT paging structures and per-CPU state across all
 * processors, and remapping a NEW BUILD without rebooting means two generations can briefly coexist.
 *
 * The cost is honest: 16 MB of RAM permanently marked firmware-reserved, on every boot, whether a
 * runtime map ever happens or not. That is the price of not touching kernel pool, and it buys the
 * stable unmap/remap cycle v1 never achieved.
 */
#define NXC_ARENA_BYTES   (16u * 1024u * 1024u)

STATIC UINT8*                  mArenaBase       = NULL;
STATIC UINTN                   mArenaSize       = 0;

/**
 * Record one NXC_BOOTFLAG_* phase bit, from anywhere in the DXE.
 *
 * Exists because the DXE's phases are spread across three files -- MapNexusCore, PatchWinload and
 * NexusBootDxe -- and only this one owns mBootBlock. Callers should not have to know that, and should
 * certainly not each re-derive a NULL check.
 *
 * NULL-safe on purpose: several phases can run before the block is addressable (or after a failed
 * reservation), and a phase flag is a diagnostic. It must never be the thing that faults.
 */
VOID
EFIAPI
NexusCoreSetBootFlag(
	IN UINT32 Flag
	)
{
	if (mBootBlock != NULL)
		mBootBlock->BootFlags |= Flag;
}

/**
 * Record WHY a boot phase gave up: the source line of the refusal.
 *
 * ⚠ FIRST WRITER WINS. A refusal usually cascades -- winload declines, so bind never runs, so the
 * launch never fires -- and the FIRST one is the cause while everything after it is consequence.
 * Last-writer-wins would bury the answer under its own after-effects.
 *
 * NULL-safe for the same reason as the flag setter: a diagnostic must never be the thing that faults.
 */
VOID
EFIAPI
NexusCoreSetRefusalLine(
	IN UINT32 Line
	)
{
	if (mBootBlock != NULL && mBootBlock->DxeRefusalLine == 0)
		mBootBlock->DxeRefusalLine = Line;
}

/*
 * The kernel patch's own refusal slot. SEPARATE from DxeRefusalLine above, and the separation is the
 * entire point -- see the KernelPatchLine comment in NexusCoreBoot.h.
 *
 * Short version: that field is first-writer-wins and PatchNtoskrnl runs BEFORE bind, while its
 * failures are non-fatal by design. Sharing the slot would let an advisory failure squat on it and
 * hide the bind failure that actually stopped the load.
 */
VOID
EFIAPI
NexusCoreSetKernelPatchLine(
	IN UINT32 Line
	)
{
	if (mBootBlock != NULL && mBootBlock->KernelPatchLine == 0)
		mBootBlock->KernelPatchLine = Line;
}

/*
 * Publish where g_PgContext lives, so usermode can read the pointer and decide for itself
 * whether the defusal took. See NEXUS_CORE_BOOT_BLOCK::PgContextRva.
 *
 * Last-write-wins, and there is one writer. A zero means the locator did not find it, which is
 * a different and more interesting statement than "nobody called this".
 */
VOID
EFIAPI
NexusCoreSetPgContextRva(
	IN UINT32 Rva
	)
{
	if (mBootBlock != NULL)
		mBootBlock->PgContextRva = Rva;
}

/*
 * The kernel build the PatchGuard signatures were matched against.
 *
 * NOT first-writer-wins: there is exactly one writer, and last-write-wins would be equally correct.
 * Written plainly so a zero means "never read the version resource" rather than "wrote zero".
 */
/*
 * WHICH PlatformRuntimeDxe.efi is running -- our own PE TimeDateStamp.
 *
 * Separate from PayloadIdent on purpose: that one identifies the embedded DRIVER, and a DXE-only
 * change leaves it unchanged. Both are needed to say "this exact pair of binaries is live".
 */
VOID
EFIAPI
NexusCoreSetDxeIdent(
	IN UINT32 Ident
	)
{
	if (mBootBlock != NULL)
		mBootBlock->DxeIdent = Ident;
}

/*
 * ABI 17. Hand the software-TPM regions to ring 0.
 *
 * Called after NexusTpmTransportInit(), and like every other setter here it is NULL-safe: the
 * boot block does not exist until NexusCoreReserve() has run, and a write before that is
 * silently dropped. That ordering trap has bitten this file twice -- the HOOKED flag and the DXE
 * ident both shipped broken because they were set before the block existed -- so the transport
 * init is deliberately sequenced AFTER the reserve, and this is called from there.
 */
VOID
EFIAPI
NexusCoreSetTpmRegions(
	IN UINT64 TransportBase,
	IN UINT32 TransportSize,
	IN UINT64 StateBase,
	IN UINT32 StateSize,
	IN UINT64 Epoch
	)
{
	if (mBootBlock != NULL)
	{
		mBootBlock->TpmTransportBase = TransportBase;
		mBootBlock->TpmTransportSize = TransportSize;
		mBootBlock->TpmStateBase     = StateBase;
		mBootBlock->TpmStateSize     = StateSize;
		mBootBlock->TpmBootEpoch     = Epoch;
	}
}

/*
 * ABI 18. What the firmware published about TPM, so the answer survives to the OS instead of
 * living only on the boot screen.
 */
VOID
EFIAPI
NexusCoreSetFirmwareTcg(
	IN UINT32 Flags
	)
{
	if (mBootBlock != NULL)
		mBootBlock->TpmFirmwareTcg = Flags;
}

/*
 * ABI 19. The TCG2 event log extent.
 *
 * Same NULL-safe contract as every other setter here, and called AFTER NexusTcg2Install() for
 * the same ordering reason: the log does not exist until the protocol is installed, and a
 * write before that would publish a zero extent that looks exactly like "TCG2 stood down".
 */
VOID
EFIAPI
NexusCoreSetTpmEventLog(
	IN UINT64 Base,
	IN UINT32 Size
	)
{
	if (mBootBlock != NULL)
	{
		mBootBlock->TpmEventLogBase = Base;
		mBootBlock->TpmEventLogSize = Size;
	}
}

VOID
EFIAPI
NexusCoreSetKernelBuild(
	IN UINT32 BuildNumber,
	IN UINT32 Revision
	)
{
	if (mBootBlock != NULL)
	{
		mBootBlock->KernelBuild    = BuildNumber;
		mBootBlock->KernelRevision = Revision;
	}
}

VOID*
EFIAPI
NexusCoreGetBootBlock(
	VOID
	)
{
	return mBootBlock;
}

/**
 * Resolve one import by name against ntoskrnl, reusing NexusPe.c's existing walker.
 *
 * NOTE ON HASHING, since the reference implementations do it and we deliberately do not: RedLotus
 * hashes each imported name and looks it up by hash. That buys NOTHING here -- the names are stored
 * in NexusCore's own import table, which we are reading them out of, so they exist in the payload
 * either way. Hashing only avoids a string compare. Real import hiding means emitting no import
 * table at all, which is a payload-side change for later, not a mapper trick.
 */
STATIC
VOID*
ResolveNtImport(
	IN UINT8* NtKernelBase,
	IN PEFI_IMAGE_NT_HEADERS NtKernelHeaders,
	IN CONST CHAR8* Name
	)
{
	VOID* Address = GetProcedureAddress((UINTN)NtKernelBase, NtKernelHeaders, Name);

	/*
	 * Range-check the result. GetProcedureAddress returning something outside ntoskrnl would mean
	 * a malformed export directory, and writing that into an IAT entry produces a jump to garbage
	 * on first call -- a bugcheck with no breadcrumb. Cheap to check, impossible to debug later.
	 */
	if (Address != NULL)
	{
		CONST UINTN Start = (UINTN)NtKernelBase;
		CONST UINTN End = Start + NtKernelHeaders->OptionalHeader.SizeOfImage;
		if ((UINTN)Address < Start || (UINTN)Address >= End)
			return NULL;
	}
	return Address;
}

/**
 * Seed the /GS security cookie in the mapped image.
 *
 * WHY THE MAPPER OWNS THIS: a manually-mapped driver has no CRT init, so nothing ever calls
 * __security_init_cookie(). BlackAlien's testdriver states outright that a mapped driver must NOT
 * call it itself. If the image has a load config with a SecurityCookie pointer and we leave it at
 * its file value, any /GS-instrumented function corrupts its own frame check.
 *
 * Our payload DOES carry a load config (measured at build time: 328 bytes), so this is live code,
 * not a defensive branch -- even though stage 1's driver disables GS checks per translation unit.
 *
 * IMPROVEMENT over the reference: RedLotus XORs a few values together and accepts the result. We
 * additionally reject the x64 DEFAULT cookie value and zero. Both are values the check treats as
 * "uninitialised", which defeats the point of setting it at all.
 */
STATIC
VOID
SeedSecurityCookie(
	IN UINT8* Image,
	IN UINTN ImageSize
	)
{
	if (NXC_PAYLOAD_LCFG_SIZE == 0 || NXC_PAYLOAD_LCFG_RVA == 0)
		return;
	if (NXC_PAYLOAD_LCFG_RVA + NXC_PAYLOAD_LCFG_SIZE > ImageSize)
		return;

	/*
	 * SecurityCookie is at offset 0x58 in IMAGE_LOAD_CONFIG_DIRECTORY64. Guard on the directory
	 * being large enough to actually contain it -- older/smaller load configs do not.
	 */
	CONST UINTN CookieFieldOffset = 0x58;
	if (NXC_PAYLOAD_LCFG_SIZE < CookieFieldOffset + sizeof(UINT64))
		return;

	UINT64* CookieSlotVa = (UINT64*)(Image + NXC_PAYLOAD_LCFG_RVA + CookieFieldOffset);

	/*
	 * The field holds a VIRTUAL ADDRESS of the cookie variable, expressed against the image's LINK
	 * base. Relocations have already rewritten it to our mapped base, so convert back to an RVA
	 * and bounds-check before dereferencing.
	 */
	CONST UINT64 CookieVa = *CookieSlotVa;
	if (CookieVa < (UINT64)(UINTN)Image)
		return;
	CONST UINTN CookieRva = (UINTN)(CookieVa - (UINT64)(UINTN)Image);
	if (CookieRva + sizeof(UINT64) > ImageSize)
		return;

	/* Mix several independent sources; TSC alone is guessable across a reboot. */
	UINT64 Cookie = AsmReadTsc();
	Cookie ^= ((UINT64)(UINTN)Image << 13);
	Cookie ^= (UINT64)ImageSize * 0x9E3779B97F4A7C15ULL;
	Cookie *= 0xFF51AFD7ED558CCDULL;
	Cookie ^= (Cookie >> 33);

	/* x64 keeps the low 48 bits. */
	Cookie &= 0x0000FFFFFFFFFFFFULL;

	/*
	 * Reject the two values the GS check reads as "never initialised": zero, and the compiler's
	 * default. Landing on either silently disables the protection we are here to enable.
	 */
	if (Cookie == 0 || Cookie == 0x00002B992DDFA232ULL)
		Cookie = 0x0000123456789ABCULL ^ AsmReadTsc();

	*(UINT64*)(Image + CookieRva) = Cookie;
}

/**
 * Erase the import metadata from the MAPPED image, after every import has been bound.
 *
 * ============================================================================================
 * WHY -- and what this does NOT fix
 * ============================================================================================
 *
 * MEASURED on the stage-1 payload, the kernel-resident image exposes:
 *
 *     6 import NAMES  vDbgPrintExWithPrefix, KeGetCurrentIrql, KeDelayExecutionThread,
 *                     ExAllocatePool2, ExFreePoolWithTag, RtlInitUnicodeString
 *     1 module NAME   "ntoskrnl.exe"
 *
 * Together those are a precise capability fingerprint: they say what kernel facilities we use,
 * without needing a single symbol. Once bound, NOTHING reads them again -- the code calls through
 * the IAT -- so they are pure liability and can be zeroed with no behavioural cost.
 *
 * ⚠ WHAT REMAINS, deliberately, so nobody mistakes this for full import hiding:
 *
 *  1. The IAT itself. Those resolved pointers ARE how the code calls nt, so they must stay.
 *
 *     ⚠ AND THERE IS A PUBLISHED DETECTION THAT TARGETS EXACTLY THIS -- found by the tier-2 web
 *     pass, after this code was written (tulach.cc, "Detecting manually mapped
 *     drivers"). The method: scan for absolute indirect jumps (FF 25), check the instruction lies
 *     inside a kernel address range, resolve the import it references, and see whether it points
 *     into ntoskrnl. Code that calls nt through an IAT thunk but does NOT belong to any known
 *     module is a manually mapped driver.
 *
 *     SCRUBBING NAMES DOES NOTHING AGAINST IT. It never reads a name. So option C -- what this
 *     function does -- is genuinely useful against a string/PE-header scan and USELESS against this.
 *     Defeating it needs the payload to stop having an IAT at all: hash-resolved pointers held in
 *     non-contiguous storage, called without FF 25 thunks. That is the "option B" written off
 *     earlier as low marginal value -- a judgement made WITHOUT this evidence and now worth
 *     revisiting on its merits.
 *  2. The DXE's embedded copy (NxcPayloadBytes) is untouched -- the at-rest payload inside
 *     PlatformRuntimeDxe.efi keeps its full import table. That file is already a known-ours artifact
 *     on the ESP, so the marginal gain from encrypting it is smaller than it first appears.
 *  3. THE LOUDER LEAK IS NOT IMPORTS AT ALL. The same measurement found the project name "Nexus" x5
 *     and 6 DbgPrint format strings including "no boot block -- not loaded by the Nexus mapper" --
 *     which name the project and DESCRIBE THE MECHANISM in cleartext. Removing logging would beat
 *     this change outright.
 *
 *     That is DEFERRED ON PURPOSE (user's call): logging repeatedly earned its keep
 *     while developing v1, and the boot block reports coarse status, not the mid-debug granularity
 *     DbgPrint gives. Revisit as a far-future hardening step, not now.
 *
 * Eliminating the import table entirely (payload carries salted hashes, no descriptors) is the
 * stronger option, but costs indirect calls at every site, dumpbin verification -- which is what
 * caught that our imports were nt-only -- and symbolised crash dumps on a kernel component that is
 * about to grow threads and HV interaction. Not worth it for the residual gain over this.
 */
STATIC
VOID
ScrubImportMetadata(
	VOID
	)
{
	UINT32 DirSize = 0;
	VOID* ImportDir = RtlpImageDirectoryEntryToDataEx(
		mImageBase, TRUE, EFI_IMAGE_DIRECTORY_ENTRY_IMPORT, &DirSize);
	if (ImportDir == NULL || DirSize == 0)
	{
		/*
		 * No import directory at all -- the payload calls nt through the NexusNtApi pointer table, so
		 * there is nothing to erase. Recorded as its OWN flag rather than left silent: the first boot
		 * after the import table was removed reported "imports scrubbed: no", which reads as a fault
		 * when it is in fact the strongest possible result.
		 */
		if (mBootBlock != NULL)
			mBootBlock->BootFlags |= NXC_BOOTFLAG_NO_IMPORTS;
		return;
	}

	EFI_IMAGE_IMPORT_DESCRIPTOR* Desc = (EFI_IMAGE_IMPORT_DESCRIPTOR*)ImportDir;

	/*
	 * Walk the descriptors a SECOND time, purely to erase. Deliberately separate from the binding
	 * walk: scrubbing as we bind would destroy the names mid-iteration, and a partially-scrubbed
	 * table is worse than either state -- it would leave some names behind while making the failure
	 * look like success.
	 */
	for (; Desc->Name != 0; Desc++)
	{
		if ((UINTN)Desc->Name >= mImageSize)
			break;

		CONST UINT32 FirstThunkRva = (UINT32)(UINTN)Desc->FirstThunk;
		CONST UINT32 LookupRva = Desc->Characteristics != 0 ? Desc->Characteristics : FirstThunkRva;

		/* Zero each imported function's hint+name string, reached through the LOOKUP thunks. */
		if (LookupRva != 0 && LookupRva < mImageSize)
		{
			UINT64* Lookup = (UINT64*)(mImageBase + LookupRva);
			for (; *Lookup != 0; Lookup++)
			{
				if ((*Lookup & 0x8000000000000000ULL) != 0)
					continue;               /* by ordinal: no name string to erase */

				CONST UINT32 NameRva = (UINT32)(*Lookup & 0xFFFFFFFFULL);
				if (NameRva + sizeof(UINT16) >= mImageSize)
					continue;

				/* IMAGE_IMPORT_BY_NAME = USHORT Hint + NUL-terminated ASCII. */
				CHAR8* Name = (CHAR8*)(mImageBase + NameRva + sizeof(UINT16));
				UINTN Len = 0;
				while (NameRva + sizeof(UINT16) + Len < mImageSize && Name[Len] != '\0')
					Len++;
				ZeroMem(mImageBase + NameRva, sizeof(UINT16) + Len);
			}

			/* The lookup array is only ever read by a loader. We are the loader, and we are done. */
			ZeroMem(mImageBase + LookupRva,
			        (UINTN)((UINT8*)Lookup - (mImageBase + LookupRva)) + sizeof(UINT64));
		}

		/* "ntoskrnl.exe" -- names the one module we depend on. */
		CHAR8* ModuleName = (CHAR8*)(mImageBase + Desc->Name);
		UINTN ModLen = 0;
		while ((UINTN)Desc->Name + ModLen < mImageSize && ModuleName[ModLen] != '\0')
			ModLen++;
		ZeroMem(ModuleName, ModLen);
	}

	/*
	 * Finally the descriptor array, and the data-directory entry pointing at it, so a PE parser sees
	 * no import table rather than an intact table full of blanked strings.
	 */
	ZeroMem(ImportDir, DirSize);

	CONST PEFI_IMAGE_NT_HEADERS Nt = RtlpImageNtHeaderEx(mImageBase, mImageSize);
	if (Nt != NULL &&
	    Nt->OptionalHeader.NumberOfRvaAndSizes > EFI_IMAGE_DIRECTORY_ENTRY_IMPORT)
	{
		Nt->OptionalHeader.DataDirectory[EFI_IMAGE_DIRECTORY_ENTRY_IMPORT].VirtualAddress = 0;
		Nt->OptionalHeader.DataDirectory[EFI_IMAGE_DIRECTORY_ENTRY_IMPORT].Size = 0;
	}

	if (mBootBlock != NULL)
		mBootBlock->BootFlags |= NXC_BOOTFLAG_IMPORTS_SCRUBBED;

	//
	// VERIFY THE OUTCOME, not just that this function ran.
	//
	// The IMPORTS_SCRUBBED flag above only proves the code executed. It cannot detect a PARTIAL
	// scrub -- a descriptor loop that exited early, a name string missed because a length walk hit
	// the image bound, an import table with two descriptors where we assumed one. That is exactly
	// the blind-check shape this project keeps being bitten by: a signal that cannot show the
	// failure being read as proof there is none.
	//
	// So re-scan our own mapped image for the residue and record whether it is actually gone.
	//
	// ⚠ SCAN FOR "ntoskrnl" ONLY -- deliberately NOT for API names like "ExAllocatePool2". Those
	// legitimately still appear in the driver's DbgPrint FORMAT STRINGS ("ExAllocatePool2 +
	// ExFreePoolWithTag OK"), which are not import metadata and are staying for now. Scanning for
	// them would report a permanent false failure and the check would be discarded as noisy.
	// "ntoskrnl" was measured to occur exactly once, in the import module name, so its absence is
	// a clean signal.
	//
	STATIC CONST CHAR8 Needle[] = "ntoskrnl";
	CONST UINTN NeedleLen = sizeof(Needle) - 1;
	BOOLEAN Found = FALSE;

	for (UINTN i = 0; i + NeedleLen <= mImageSize && !Found; i++)
	{
		UINTN j = 0;
		while (j < NeedleLen)
		{
			CHAR8 c = (CHAR8)mImageBase[i + j];
			if (c >= 'A' && c <= 'Z')
				c = (CHAR8)(c + ('a' - 'A'));   /* case-insensitive: "NTOSKRNL.EXE" is legal too */
			if (c != Needle[j])
				break;
			j++;
		}
		if (j == NeedleLen)
			Found = TRUE;
	}

	if (!Found && mBootBlock != NULL)
		mBootBlock->BootFlags |= NXC_BOOTFLAG_SCRUB_VERIFIED;
}

EFI_STATUS
EFIAPI
NexusCoreReserve(
	VOID
	)
{
	if (mStaged)
		return EFI_SUCCESS;

	/*
	 * VERIFY BEFORE ANYTHING ELSE. A stale or truncated embed is the realistic build accident, and
	 * its failure mode without this check is an unexplained early-boot hang -- our single most
	 * expensive failure, because each diagnosis costs a reboot cycle. Reuses the Sha256 already
	 * present for Tier 3.
	 */
	UINT8 Digest[32];
	Sha256(NxcPayloadBytes, NXC_PAYLOAD_SIZE, Digest);
	if (CompareMem(Digest, NxcPayloadSha256, sizeof(Digest)) != 0)
		return EFI_CRC_ERROR;

	/*
	 * ============================================================================================
	 * AND CROSS-CHECK THE DERIVED CONSTANTS AGAINST THE BYTES. The hash cannot do this.
	 * ============================================================================================
	 *
	 *  The SHA-256 above compares the payload against a digest that
	 * embed_driver.py computed FROM THAT SAME PAYLOAD. It is a real and useful check -- it catches a
	 * stale or truncated embed, which is the common build accident -- but it is a mirror: the thing
	 * checked and the thing checking it came from one source. It cannot detect a tool that read the
	 * PE wrongly, because the tool would then emit a correct hash beside wrong metadata.
	 *
	 * And the nine NXC_PAYLOAD_* constants are exactly that: embed_driver.py's own hand-written PE
	 * parse. That is the same class of code as the NXP_OPT64 struct which carried a PE32-only
	 * BaseOfData field and silently decoded every field after ImageBase four bytes late, breaking the
	 * runtime mapper completely while every existing check passed.
	 *
	 * Each constant has a distinct failure if it is wrong, and none of them announce themselves:
	 *   SIZE_OF_IMAGE wrong -> we reserve the wrong amount; sections land outside or space is wasted
	 *   SIZE_OF_HDRS wrong  -> the header copy takes the wrong span, so the section table we then
	 *                          walk from the MAPPED image is garbage
	 *   ENTRY_RVA wrong     -> NexusCoreTryLaunch calls the wrong address, in kernel mode
	 *   IMAGE_BASE wrong    -> the relocation delta is wrong and every absolute in the image is
	 *                          rewritten to nonsense
	 *
	 * So compare them to what the EMBEDDED BYTES actually say. We parse that PE a few lines below
	 * anyway; doing it here costs four compares and makes the check INDEPENDENT -- two different code
	 * paths (a Python tool and this parser) have to agree, which is what the hash on its own can never
	 * establish.
	 *
	 * Before the allocation deliberately: a payload we do not trust should not get memory.
	 */
	{
		CONST EFI_IMAGE_DOS_HEADER* CONST SrcDos = (CONST EFI_IMAGE_DOS_HEADER*)NxcPayloadBytes;
		if (SrcDos->e_magic != EFI_IMAGE_DOS_SIGNATURE ||
		    (UINTN)SrcDos->e_lfanew + sizeof(EFI_IMAGE_NT_HEADERS64) > NXC_PAYLOAD_SIZE)
			return EFI_VOLUME_CORRUPTED;

		CONST PEFI_IMAGE_NT_HEADERS SrcNt =
			(PEFI_IMAGE_NT_HEADERS)(NxcPayloadBytes + SrcDos->e_lfanew);

		if (SrcNt->Signature != EFI_IMAGE_NT_SIGNATURE                              ||
		    SrcNt->OptionalHeader.SizeOfImage        != NXC_PAYLOAD_SIZE_OF_IMAGE   ||
		    SrcNt->OptionalHeader.SizeOfHeaders      != NXC_PAYLOAD_SIZE_OF_HDRS    ||
		    SrcNt->OptionalHeader.AddressOfEntryPoint!= NXC_PAYLOAD_ENTRY_RVA       ||
		    SrcNt->OptionalHeader.ImageBase          != NXC_PAYLOAD_IMAGE_BASE)
		{
			PRINT_KERNEL_PATCH_MSG(
				L"[NexusCore] embedded constants disagree with the payload bytes -- REFUSED\r\n");
			return EFI_VOLUME_CORRUPTED;
		}
	}

	/*
	 * EfiRuntimeServicesCode, not pool and not EfiLoaderData: it must survive ExitBootServices and
	 * be executable in kernel context. This is the allocation type the public mappers cannot use,
	 * because they only get control once the kernel is already running.
	 */
	EFI_PHYSICAL_ADDRESS Pages = 0;
	CONST UINTN PageCount = EFI_SIZE_TO_PAGES(NXC_TOTAL_BYTES);
	EFI_STATUS Status = gBS->AllocatePages(AllocateAnyPages, EfiRuntimeServicesCode,
	                                       PageCount, &Pages);
	if (EFI_ERROR(Status))
		return EFI_OUT_OF_RESOURCES;

	UINT8* Image = (UINT8*)(UINTN)Pages;
	ZeroMem(Image, NXC_TOTAL_BYTES);

	/* Headers first, then each section to its RVA -- a raw file is not a mapped image. */
	CopyMem(Image, NxcPayloadBytes, NXC_PAYLOAD_SIZE_OF_HDRS);

	CONST EFI_IMAGE_DOS_HEADER* Dos = (CONST EFI_IMAGE_DOS_HEADER*)NxcPayloadBytes;
	CONST PEFI_IMAGE_NT_HEADERS Nt =
		(PEFI_IMAGE_NT_HEADERS)(NxcPayloadBytes + Dos->e_lfanew);
	CONST EFI_IMAGE_SECTION_HEADER* Sections = (CONST EFI_IMAGE_SECTION_HEADER*)
		((UINT8*)&Nt->OptionalHeader + Nt->FileHeader.SizeOfOptionalHeader);

	for (UINT16 i = 0; i < Nt->FileHeader.NumberOfSections; i++)
	{
		CONST EFI_IMAGE_SECTION_HEADER* S = &Sections[i];
		if (S->SizeOfRawData == 0)
			continue;   /* .bss-style: already zeroed above */

		/* Bounds-check both ends; a malformed section table must not write outside the reservation. */
		if ((UINTN)S->PointerToRawData + S->SizeOfRawData > NXC_PAYLOAD_SIZE ||
		    (UINTN)S->VirtualAddress + S->SizeOfRawData > NXC_PAYLOAD_SIZE_OF_IMAGE)
		{
			gBS->FreePages(Pages, PageCount);
			return EFI_VOLUME_CORRUPTED;
		}

		CopyMem(Image + S->VirtualAddress,
		        NxcPayloadBytes + S->PointerToRawData,
		        S->SizeOfRawData);
	}

	mImageBase = Image;
	mImageSize = NXC_PAYLOAD_SIZE_OF_IMAGE;
	mBootBlock = (NEXUS_CORE_BOOT_BLOCK*)(Image + NXC_BLOCK_OFFSET);

	/*
	 * Fill the INPUT half now and zero the OUTPUT half. Doing it here rather than in phase 2 keeps
	 * phase 2 free of writes it does not need, and means the block is inspectable even if binding
	 * later fails -- which is the case where we most want to know how far we got.
	 */
	mBootBlock->Magic = NEXUS_CORE_BOOT_MAGIC;
	mBootBlock->Abi = NEXUS_CORE_BOOT_ABI;
	mBootBlock->InputSize = (NXC_U32)sizeof(NEXUS_CORE_BOOT_BLOCK);
	mBootBlock->MappedImageBase = (NXC_U64)(UINTN)Image;
	mBootBlock->MappedImageSize = (NXC_U32)NXC_PAYLOAD_SIZE_OF_IMAGE;
	mBootBlock->OriginalEntry = 0;
	mBootBlock->BootFlags = 0;

	/*
	 * ⚠ SET AFTER THE ZERO, NOT BEFORE. This was originally written where the block first becomes
	 * addressable, ~40 lines up -- and this line then wiped it, every boot.
	 *
	 * CAUGHT by printing the phase trail on a HEALTHY boot, which showed
	 * "[ ] entry+reserve [x] winload patched [x] SVAM [x] bind" -- causally impossible, since bind
	 * cannot run unless the DXE entered. That is the whole argument for verifying a detector while
	 * things work: on a FAILING boot the same missing bit would have read as "the DXE never ran" and
	 * sent the diagnosis to entirely the wrong place. A broken detector is worse than none, because it
	 * is believed.
	 *
	 * Reaching this line proves both facts, so both bits are set here: the entry ran, and the
	 * reservation succeeded (the block lives inside the reserved image).
	 */
	mBootBlock->BootFlags |= (NXC_BOOTFLAG_DXE_ENTERED | NXC_BOOTFLAG_RESERVED);

	/*
	 * Stamp WHICH build this is. Taken from the payload digest already computed and verified above,
	 * so it costs a copy and identifies the embedded NexusCore exactly -- and therefore the DXE that
	 * embeds it. Without this, "is my deploy live?" is answered by watching for a behaviour change,
	 * which is a guess, and is wrong precisely when the deploy did not take.
	 */
	CopyMem(&mBootBlock->PayloadIdent, NxcPayloadSha256, sizeof(mBootBlock->PayloadIdent));

	mBootBlock->Status = NXC_STATUS_UNSET;
	mBootBlock->Capabilities = 0;
	mBootBlock->EntryTsc = 0;
	mBootBlock->EntryIrql = 0;
	mBootBlock->EntryDurationUs = 0;   /* ABI 4: driver fills it at entry */

	/*
	 * Reserve the runtime map arena. SEPARATE allocation from the NexusCore image on purpose: the
	 * image is fixed-size and permanent, the arena is a managed pool NexusCore carves up and reuses,
	 * and keeping them apart means an arena failure cannot cost us the driver.
	 *
	 * NON-FATAL if it fails. A 16 MB contiguous reservation is not guaranteed on every firmware, and
	 * NexusCore itself works without it -- only the runtime `map` command needs it. Reporting
	 * ArenaBase = 0 lets PlatformCtl say "no arena" instead of the command failing later for an
	 * unexplained reason.
	 */
	EFI_PHYSICAL_ADDRESS ArenaPages = 0;
	CONST UINTN ArenaPageCount = EFI_SIZE_TO_PAGES(NXC_ARENA_BYTES);
	if (!EFI_ERROR(gBS->AllocatePages(AllocateAnyPages, EfiRuntimeServicesCode,
	                                  ArenaPageCount, &ArenaPages)))
	{
		mArenaBase = (UINT8*)(UINTN)ArenaPages;
		mArenaSize = NXC_ARENA_BYTES;

		/*
		 * Zero it now, while we are at boot services and can afford to. A runtime map into
		 * uninitialised memory would inherit whatever the firmware left there, and a mapped image
		 * relies on its .bss being zero -- the same reason the NexusCore reservation is zeroed.
		 */
		ZeroMem(mArenaBase, mArenaSize);

		mBootBlock->ArenaBase = (NXC_U64)(UINTN)mArenaBase;
		mBootBlock->ArenaSize = (NXC_U32)mArenaSize;
	}
	else
	{
		mBootBlock->ArenaBase = 0;
		mBootBlock->ArenaSize = 0;
	}
	mBootBlock->ArenaUsed = 0;

	mStaged = TRUE;
	return EFI_SUCCESS;
}

/*
 * ============================================================================================
 * EFI_MEMORY_ATTRIBUTES_TABLE -- the firmware's instruction to the OS about runtime memory
 * ============================================================================================
 *
 * WHY WE READ IT. Our image and our arena are both gBS->AllocatePages(EfiRuntimeServicesCode). What
 * protections they end up with in the kernel is NOT our decision and never was: modern firmware
 * publishes this table so the OS can apply W^X to runtime regions, and Windows acts on it.
 *
 * The EDK2 reference implementation (MemoryAttributesTable.c, EnforceMemoryMapAttribute) marks ALL
 * EfiRuntimeServicesCode with EFI_MEMORY_RO and ALL EfiRuntimeServicesData with EFI_MEMORY_XP --
 * not just image sections. If this firmware does the same and Windows honours it, then our arena is
 * READ-ONLY at runtime and the first allocation out of it faults. That is a functional bug sitting
 * underneath task 7, not a hardening detail, and NOTHING we currently run could see it.
 *
 * So: read what was actually published, and report it beside the PTE bits the driver measures. If
 * the measurement is surprising, the cause is in the next field along instead of being a fresh
 * investigation.
 *
 * ⚠ TIMING. Called from NexusCoreBind, which runs inside the winload hook while BOOT SERVICES ARE
 * STILL UP -- the latest point where the configuration table is both final (every runtime image has
 * loaded) and safely readable. Reading it at DXE entry instead would catch a half-built table.
 *
 * Types are declared locally rather than pulled from MdePkg's Guid/MemoryAttributesTable.h: this
 * file already avoids reaching into headers the VisualUefi build may not carry, and the structure
 * is four UINT32s followed by standard descriptors. A local declaration cannot be broken by an SDK
 * that turns out not to ship the header -- a failure this project has hit twice (AsmReadCr8,
 * RtlAddGrowableFunctionTable), both times at LINK, after the code read as correct.
 */
#define NXC_EFI_MEMORY_ATTRIBUTES_TABLE_GUID \
	{ 0xdcfa911d, 0x26eb, 0x469f, { 0xa2, 0x20, 0x38, 0xb7, 0xdc, 0x46, 0x12, 0x20 } }

#define NXC_EFI_MEMORY_RO   0x0000000000020000ULL
#define NXC_EFI_MEMORY_XP   0x0000000000004000ULL

typedef struct
{
	UINT32 Version;
	UINT32 NumberOfEntries;
	UINT32 DescriptorSize;
	UINT32 Flags;
	/* EFI_MEMORY_DESCRIPTOR Entry[NumberOfEntries] follows, DescriptorSize apart. */
} NXC_EFI_MEMORY_ATTRIBUTES_TABLE;

/**
 * Find the descriptor covering @p Address and fold its attributes into @p Flags.
 *
 * Descriptors are walked with DescriptorSize, NOT sizeof(EFI_MEMORY_DESCRIPTOR). The UEFI spec
 * allows the firmware to use a larger stride, and assuming sizeof() is the classic way to read a
 * memory map as convincing garbage.
 */
STATIC VOID
NexusCoreClassifyRange(
	IN CONST NXC_EFI_MEMORY_ATTRIBUTES_TABLE* Table,
	IN UINT64                                 Address,
	IN UINT32                                 CoveredFlag,
	IN UINT32                                 RoFlag,
	IN UINT32                                 XpFlag,
	IN OUT UINT32*                            Flags
	)
{
	CONST UINT8* Entry = (CONST UINT8*)(Table + 1);

	for (UINT32 i = 0; i < Table->NumberOfEntries; i++, Entry += Table->DescriptorSize)
	{
		CONST EFI_MEMORY_DESCRIPTOR* Desc = (CONST EFI_MEMORY_DESCRIPTOR*)Entry;
		CONST UINT64 Start = (UINT64)Desc->PhysicalStart;
		CONST UINT64 End   = Start + (UINT64)Desc->NumberOfPages * EFI_PAGE_SIZE;

		if (Address < Start || Address >= End)
			continue;

		*Flags |= CoveredFlag;
		if (Desc->Attribute & NXC_EFI_MEMORY_RO)
			*Flags |= RoFlag;
		if (Desc->Attribute & NXC_EFI_MEMORY_XP)
			*Flags |= XpFlag;
		return;
	}
}

/** Record what the firmware published about our two regions. Never fails the boot. */
STATIC VOID
NexusCoreProbeMemoryAttributes(
	VOID
	)
{
	if (mBootBlock == NULL)
		return;

	CONST EFI_GUID MatGuid = NXC_EFI_MEMORY_ATTRIBUTES_TABLE_GUID;
	UINT32 Flags = 0;

	for (UINTN i = 0; i < gST->NumberOfTableEntries; i++)
	{
		if (!CompareGuid(&gST->ConfigurationTable[i].VendorGuid, &MatGuid))
			continue;

		CONST NXC_EFI_MEMORY_ATTRIBUTES_TABLE* Table =
			(CONST NXC_EFI_MEMORY_ATTRIBUTES_TABLE*)gST->ConfigurationTable[i].VendorTable;
		if (Table == NULL || Table->DescriptorSize == 0)
			break;

		Flags |= NXC_MAT_PRESENT;

		if (mArenaBase != NULL)
			NexusCoreClassifyRange(Table, (UINT64)(UINTN)mArenaBase,
			                       NXC_MAT_ARENA_COVERED, NXC_MAT_ARENA_RO, NXC_MAT_ARENA_XP,
			                       &Flags);
		if (mImageBase != NULL)
		{
			NexusCoreClassifyRange(Table, (UINT64)(UINTN)mImageBase,
			                       NXC_MAT_IMAGE_COVERED, NXC_MAT_IMAGE_RO, NXC_MAT_IMAGE_XP,
			                       &Flags);

			/*
			 * And the CODE, separately. mImageBase is the PE HEADER page, and the firmware splits a
			 * runtime image so headers/data carry XP while code carries RO -- so classifying only the
			 * base reports XP and invites the conclusion that the whole image is no-execute. It is
			 * not; the entry point lives in a different descriptor. Sampling both shows the split
			 * instead of leaving one page to be over-generalised.
			 */
			NexusCoreClassifyRange(Table, (UINT64)(UINTN)mImageBase + NXC_PAYLOAD_ENTRY_RVA,
			                       NXC_MAT_CODE_COVERED, NXC_MAT_CODE_RO, NXC_MAT_CODE_XP,
			                       &Flags);
		}

		PRINT_KERNEL_PATCH_MSG(L"[NexusCore] MAT v%u, %u entries, stride %u -> flags 0x%X\r\n",
		                       Table->Version, Table->NumberOfEntries, Table->DescriptorSize, Flags);
		break;
	}

	if ((Flags & NXC_MAT_PRESENT) == 0)
		PRINT_KERNEL_PATCH_MSG(L"[NexusCore] no EFI_MEMORY_ATTRIBUTES_TABLE published\r\n");

	mBootBlock->EfiMatFlags = Flags;
}

EFI_STATUS
EFIAPI
NexusCoreBind(
	IN UINT8* NtKernelBase,
	IN PEFI_IMAGE_NT_HEADERS NtKernelHeaders,
	OUT VOID** OutEntry
	)
{
	/*
	 * Recorded on ARRIVAL, before any check below can refuse. "Bind was reached and gave up" and
	 * "bind was never called" are different failures with different suspects, and from a status read
	 * they used to look identical -- which is exactly why these flags exist.
	 */
	NexusCoreSetBootFlag(NXC_BOOTFLAG_BIND_RAN);

	if (OutEntry != NULL)
		*OutEntry = NULL;
	if (!mStaged || mImageBase == NULL)
		return EFI_NOT_READY;
	if (mBound)
	{
		/* Idempotent: winload can re-enter, and re-relocating would double-apply the delta. */
		if (OutEntry != NULL)
			*OutEntry = mImageBase + NXC_PAYLOAD_ENTRY_RVA;
		return EFI_SUCCESS;
	}
	if (NtKernelBase == NULL || NtKernelHeaders == NULL)
		return EFI_INVALID_PARAMETER;

	/*
	 * Publish ntoskrnl's location for NexusCore's RUNTIME mapper (ABI 3). This is the one place both
	 * values are known for free -- the winload hook already resolved them to patch the kernel -- and
	 * handing them over saves the driver from deriving the base by scanning kernel memory for "MZ".
	 */
	if (mBootBlock != NULL)
	{
		mBootBlock->KernelBase = (NXC_U64)(UINTN)NtKernelBase;
		mBootBlock->KernelSize = (NXC_U32)NtKernelHeaders->OptionalHeader.SizeOfImage;

		/*
		 * (!) PgContextRva IS NOT CLEARED HERE, AND THAT MATTERS. This was `Reserved1 = 0`, a
		 * harmless zeroing of padding -- until ABI 20 gave the word a meaning. PatchNtoskrnl runs
		 * BEFORE this point and has already published the RVA, so zeroing it here would silently
		 * erase the answer `pgdefuse verify` exists to read, on every boot, with no symptom other
		 * than the verb reporting "not located".
		 */
	}

	/*
	 * ABI 5. Record the firmware's runtime-memory attributes while boot services are still up -- this
	 * is the last moment the configuration table is both final and safe to read, and it is the CAUSE
	 * of whatever page protections the driver goes on to measure.
	 */
	NexusCoreProbeMemoryAttributes();

	/*
	 * 1. Rebase from the link base to where we actually put it. Uses the SAME ApplyPeRelocations as
	 *    the DXE's own 4c self-relocation, deliberately -- one walker means the two cannot drift.
	 */
	CONST INT64 Delta = (INT64)((UINT64)(UINTN)mImageBase - NXC_PAYLOAD_IMAGE_BASE);
	if (Delta != 0)
		ApplyPeRelocations(mImageBase, mImageSize, Delta);

	/*
	 * 2. Bind imports against the already-mapped ntoskrnl. This is the step that needs no kernel
	 *    API and is the whole reason a kernel-side stub is unnecessary.
	 */
	UINT32 DirSize = 0;
	VOID* ImportDir = RtlpImageDirectoryEntryToDataEx(
		mImageBase, TRUE, EFI_IMAGE_DIRECTORY_ENTRY_IMPORT, &DirSize);

	if (ImportDir != NULL && DirSize != 0)
	{
		EFI_IMAGE_IMPORT_DESCRIPTOR* Desc = (EFI_IMAGE_IMPORT_DESCRIPTOR*)ImportDir;

		for (; Desc->Name != 0; Desc++)
		{
			if ((UINTN)Desc->Name >= mImageSize)
				return EFI_VOLUME_CORRUPTED;

			/*
			 * Only ntoskrnl is resolvable here. The payload is built to import from nothing else
			 * (verified on the .sys: imports == ntoskrnl.exe only), so anything else is a payload
			 * regression and must fail loudly rather than leave a null IAT entry to be called.
			 */
			CONST CHAR8* ModuleName = (CONST CHAR8*)(mImageBase + Desc->Name);
			if (AsciiStriCmp(ModuleName, "ntoskrnl.exe") != 0)
				return EFI_UNSUPPORTED;

			/*
			 * EDK2's EFI_IMAGE_IMPORT_DESCRIPTOR is NOT the Windows SDK's, and two differences bite:
			 *
			 *  - there is no OriginalFirstThunk field. That RVA lives in `Characteristics`, which is
			 *    the same union member the SDK spells OriginalFirstThunk.
			 *  - FirstThunk is DECLARED as EFI_IMAGE_THUNK_DATA*, but the on-disk field is a UINT32
			 *    RVA. Using it as a pointer would dereference an RVA as an address.
			 *
			 * And EFI_IMAGE_THUNK_DATA itself is PE32-sized (a 32-bit union), so it cannot describe
			 * our PE32+ payload's 64-bit thunks at all -- hence UINT64 arithmetic done by hand here.
			 */
			CONST UINT32 FirstThunkRva = (UINT32)(UINTN)Desc->FirstThunk;
			CONST UINT32 LookupRva = Desc->Characteristics != 0
			                       ? Desc->Characteristics
			                       : FirstThunkRva;
			if (LookupRva == 0 || LookupRva >= mImageSize || FirstThunkRva >= mImageSize)
				return EFI_VOLUME_CORRUPTED;

			UINT64* Lookup = (UINT64*)(mImageBase + LookupRva);
			UINT64* Target = (UINT64*)(mImageBase + FirstThunkRva);

			for (; *Lookup != 0; Lookup++, Target++)
			{
				/*
				 * Import by ordinal is unsupported, matching the reference implementations. Our
				 * payload imports by name only; a silent skip here would leave a NULL in the IAT
				 * that bugchecks on first call with nothing pointing at the cause.
				 */
				if ((*Lookup & 0x8000000000000000ULL) != 0)
					return EFI_UNSUPPORTED;

				CONST UINT32 NameRva = (UINT32)(*Lookup & 0xFFFFFFFFULL);
				if (NameRva + sizeof(UINT16) >= mImageSize)
					return EFI_VOLUME_CORRUPTED;

				/* IMAGE_IMPORT_BY_NAME: USHORT Hint, then the ASCII name. */
				CONST CHAR8* FuncName = (CONST CHAR8*)(mImageBase + NameRva + sizeof(UINT16));
				VOID* Resolved = ResolveNtImport(NtKernelBase, NtKernelHeaders, FuncName);
				if (Resolved == NULL)
					return EFI_NOT_FOUND;

				*Target = (UINT64)(UINTN)Resolved;
			}
		}
	}

	/* 3. GS cookie, after relocations so the load-config pointer is already rebased. */
	SeedSecurityCookie(mImageBase, mImageSize);

	//
	// 4. Locate the payload's exported NexusCoreBootSlot.
	//
	// THIS STEP WAS MISSING and cost a boot. MapNexusCore.h documented it -- "the driver
	// EXPORTS a single pointer-sized slot. The mapper resolves it ... and writes one QWORD" -- but the
	// code never did, so DriverEntry read NULL, refused with STATUS_NOT_SUPPORTED and never touched
	// the block. Symptoms were identical to a driver that faulted on its first write, and the
	// diagnosis went to the wrong suspect (the Memory Attributes Table).
	//
	// Design-doc-says-X, code-does-Y is the SAME failure class as the scope doc's action row that
	// produced the Setup bug. The lesson both times: an unimplemented documented step reads exactly
	// like a working one.
	//
	// Resolved via GetProcedureAddress against OUR OWN payload -- the same export walker used for nt,
	// pointed at a different image -- so no RVA is pinned and the payload's layout can change freely
	// anyway. Stored as an RVA, not a pointer, so phase 3's relocation cannot invalidate it.
	//
	CONST PEFI_IMAGE_NT_HEADERS PayloadNt = RtlpImageNtHeaderEx(mImageBase, mImageSize);
	if (PayloadNt != NULL)
	{
		VOID* CONST Slot = GetProcedureAddress((UINTN)mImageBase, PayloadNt, "NexusCoreBootSlot");
		if (Slot != NULL &&
			(UINTN)Slot >= (UINTN)mImageBase &&
			(UINTN)Slot + sizeof(UINT64) <= (UINTN)mImageBase + mImageSize)
		{
			mBootSlotRva = (UINT32)((UINTN)Slot - (UINTN)mImageBase);
			if (mBootBlock != NULL)
				mBootBlock->BootFlags |= NXC_BOOTFLAG_SLOT_BOUND;
		}
	}
	if (mBootSlotRva == 0)
	{
		//
		// Fail the bind. Without the slot the driver CANNOT report anything, so launching it would
		// produce precisely the silent non-result that wasted a boot. Refusing keeps the machine
		// booting normally and leaves the reason legible in the block's BootFlags.
		//
		return EFI_NOT_FOUND;
	}

	/*
	 * 5. FILL THE nt CALL TABLE. The payload carries NO import table at all (see NexusNtApi.h): it
	 *    calls nt through an exported pointer struct, so no FF 25 thunks exist for the published
	 *    manual-map scan to match. Nothing is bound until we write these, so a failure here means the
	 *    driver would fault on its first nt call -- it is fatal, not advisory.
	 */
	{
		VOID* CONST ApiExport = GetProcedureAddress((UINTN)mImageBase, PayloadNt,
													NXC_NT_API_EXPORT);
		if (ApiExport == NULL ||
			(UINTN)ApiExport < (UINTN)mImageBase ||
			(UINTN)ApiExport + sizeof(UINT64) * (1 + NXC_NT_API_COUNT) >
				(UINTN)mImageBase + mImageSize)
			return EFI_NOT_FOUND;

		UINT64* CONST Slots = (UINT64*)ApiExport;

		/*
		 * Confirm we resolved OUR table before writing a single pointer. An export that merely shares
		 * the name would otherwise get nine kernel function pointers written over it.
		 */
		if (Slots[NXC_NT_SLOT_MAGIC] != NXC_NT_API_MAGIC)
			return EFI_NOT_FOUND;

		STATIC CONST CHAR8* CONST ApiNames[] = NXC_NT_API_NAMES;

		for (UINTN i = 0; i < NXC_NT_API_COUNT; i++)
		{
			VOID* CONST Fn = ResolveNtImport(NtKernelBase, NtKernelHeaders, ApiNames[i]);
			if (Fn == NULL)
			{
				/*
				 * Refuse the whole map. A NULL slot is a call into address zero the first time that
				 * API is used -- a bugcheck with nothing pointing at the cause, which is exactly the
				 * silent-failure class this design is meant to remove.
				 */
				return EFI_NOT_FOUND;
			}
			Slots[NXC_NT_SLOT_FIRST_FN + i] = (UINT64)(UINTN)Fn;
		}
	}

	/*
	 * 6. Erase any import metadata. With the pointer table above the payload should have NO import
	 *    directory at all, so this is normally a no-op -- kept because it costs nothing and is the
	 *    backstop if a future payload change re-introduces one: it would still be scrubbed rather
	 *    than shipped intact.
	 */
	ScrubImportMetadata();

	mBound = TRUE;
	if (OutEntry != NULL)
		*OutEntry = mImageBase + NXC_PAYLOAD_ENTRY_RVA;
	return EFI_SUCCESS;
}

EFI_STATUS
EFIAPI
NexusCoreArmEntryHijack(
	IN VOID** TargetEntryPointField,
	IN VOID* TargetOriginalEntry
	)
{
	if (!mBound || mImageBase == NULL || mBootBlock == NULL)
		return EFI_NOT_READY;
	if (TargetEntryPointField == NULL || TargetOriginalEntry == NULL)
		return EFI_INVALID_PARAMETER;

	mHijackField = TargetEntryPointField;
	mHijackOriginal = TargetOriginalEntry;

	/*
	 * Hand the original entry to the driver NOW, while we are certain of it. The driver MUST call
	 * this to keep the hijacked boot driver working -- see the proxy warning in the header.
	 */
	mBootBlock->OriginalEntry = (NXC_U64)(UINTN)TargetOriginalEntry;
	return EFI_SUCCESS;
}

VOID
EFIAPI
NexusCoreRelocateForVirtual(
	VOID
	)
{
	/*
	 * ONE-SHOT. Applying the delta twice corrupts every absolute reference in the image -- the same
	 * trap scope 4c documents for the DXE itself. The flag is the only thing preventing it if the
	 * SetVirtualAddressMap callback is ever invoked more than once.
	 */
	if (mVirtualRelocated || !mStaged || mImageBase == NULL)
		return;
	mVirtualRelocated = TRUE;

	UINT8* NewBase = mImageBase;
	if (EFI_ERROR(gRT->ConvertPointer(0, (VOID**)&NewBase)))
	{
		/*
		 * ============================================================================================
		 * DISARM ON FAILURE. This used to just `return`, leaving the launch path armed.
		 * ============================================================================================
		 *
		 *  mVirtualRelocated is set ABOVE, before this call -- correctly, to
		 * make the one-shot proof against re-entry. But it means the flag records "attempted", while
		 * every reader treats it as "done".
		 *
		 * If the conversion fails we return with mImageBase still holding the PHYSICAL address, which
		 * stops meaning anything the moment SetVirtualAddressMap completes. Nothing downstream notices:
		 * NexusCoreTryLaunch gates on mLaunched/mArmed/mBound/mImageBase != NULL, all of which are
		 * still satisfied. The next hooked runtime call would then take that stale physical pointer,
		 * add the entry RVA, and CALL it -- an indirect call into whatever now lives at that physical
		 * address, in kernel mode, with no diagnostic.
		 *
		 * That is the same failure class as the unvalidated proxy pointer found in NexusCore.c an hour
		 * ago, arriving from the opposite direction: there the pointer was wrong because the DXE might
		 * write it wrong, here it is wrong because the DXE failed to update it and said nothing.
		 *
		 * So: clear mImageBase, which is the condition TryLaunch already tests. The failure becomes a
		 * launch that never fires -- visible as STATUS_UNSET with the phase trail showing SVAM reached
		 * -- instead of a wild call.
		 *
		 * The flag is recorded FIRST, through the still-valid physical block pointer: we are inside the
		 * SetVirtualAddressMap callback, so physical mappings are live for exactly this moment.
		 */
		NexusCoreSetBootFlag(NXC_BOOTFLAG_SVAM_CONVERT_FAILED);
		mImageBase = NULL;
		return;
	}

	CONST INT64 Delta = (INT64)((UINT64)(UINTN)NewBase - (UINT64)(UINTN)mImageBase);
	if (Delta == 0)
		return;

	/*
	 * Relocate while still executing at the physical address, exactly as the DXE's own 4c step
	 * does: this rewrites in-image absolutes to their future virtual values.
	 */
	ApplyPeRelocations(mImageBase, mImageSize, Delta);

	/* Follow our own pointers over, and tell the driver where it now lives. */
	if (mBootBlock != NULL)
	{
		NEXUS_CORE_BOOT_BLOCK* NewBlock = mBootBlock;
		CONST EFI_STATUS BlockConv = gRT->ConvertPointer(0, (VOID**)&NewBlock);

		/*
		 * ⚠ WRITE THROUGH THE OLD POINTER FIRST, THEN SWAP. Order corrected by review.
		 *
		 * The failure branch was silent: on a ConvertPointer error mBootBlock kept its PHYSICAL value
		 * and the code wrote through it anyway. That write SUCCEEDS -- we are inside the
		 * SetVirtualAddressMap callback, so physical mappings are still live -- and then the DXE's
		 * runtime hooks keep a physical pointer they will dereference AFTER the switch, when it means
		 * nothing. GetVariable would fault inside a runtime service, which is unrecoverable.
		 *
		 * The write itself is fine and must happen while the old mapping is valid; what was missing is
		 * noticing that the pointer we keep is stale. Recorded so a failure shows up as a diagnosable
		 * flag rather than as a firmware-service fault ten seconds later.
		 */
		mBootBlock->MappedImageBase = (NXC_U64)(UINTN)NewBase;

		if (!EFI_ERROR(BlockConv))
		{
			mBootBlock = NewBlock;
		}
		else
		{
			NexusCoreSetBootFlag(NXC_BOOTFLAG_SVAM_CONVERT_FAILED);
			mBootBlock = NULL;   /* refuse to serve a stale pointer rather than fault on it later */
		}
	}
	mImageBase = NewBase;

	/*
	 * The arena moves too -- it is EfiRuntimeServicesCode like everything else we reserved. It needs
	 * ConvertPointer but NOT ApplyPeRelocations: it is raw managed memory with no image in it yet, so
	 * there is nothing inside it holding an absolute address. Anything NexusCore later maps INTO the
	 * arena is relocated by NexusCore at that point, against the arena's then-current address.
	 *
	 * The block field must be rewritten, because the driver reads ArenaBase and would otherwise
	 * carve up a physical address that no longer means anything.
	 */
	if (mArenaBase != NULL)
	{
		UINT8* NewArena = mArenaBase;
		if (!EFI_ERROR(gRT->ConvertPointer(0, (VOID**)&NewArena)))
			mArenaBase = NewArena;
		if (mBootBlock != NULL)
			mBootBlock->ArenaBase = (NXC_U64)(UINTN)mArenaBase;
	}

	//
	// ARM phase 4 only now. We are in kernel virtual address space from this point, which is the
	// earliest moment calling into NexusCore is survivable -- v1 established the boundary the hard
	// way ("NexusCore auto-init CANNOT happen here at ExitBootServices ... would crash").
	//
	mArmed = TRUE;

	//
	// REDIRECT THE HIJACKED BOOT DRIVER'S ENTRY. This is the autonomous trigger, and it can only be
	// done HERE: the value written must be NexusCore's FINAL virtual address, which did not exist
	// until the relocation immediately above. Writing it during phase 2 would have stored a physical
	// address that this very function then invalidated -- the same ordering trap as the boot slot.
	//
	// mHijackField is a kernel VA inside winload's loader data, NOT an EFI runtime region, so it is
	// unaffected by ConvertPointer and still points where it did at phase 2.
	//
	// Writing the field is the LAST thing we do, after every other piece of state is final. If
	// anything above failed, mBound is FALSE, arming never happened, mHijackField is NULL, and the
	// hijacked driver keeps its own entry -- the machine boots normally without us.
	//
	if (mHijackField != NULL && mBootSlotRva != 0)
	{
		//
		// Publish the block pointer BEFORE redirecting. The hijacked driver's entry may be called
		// before any runtime service is, so phase 4's write cannot be relied on to happen first --
		// and a DriverEntry that finds a NULL slot refuses and reports nothing, which is exactly the
		// silent non-result that cost a boot already.
		//
		*(UINT64*)(mImageBase + mBootSlotRva) = (UINT64)(UINTN)mBootBlock;

		*mHijackField = (VOID*)(mImageBase + NXC_PAYLOAD_ENTRY_RVA);

		/*
		 * Mark the one-shot as fired. The kernel's driver-init path will now call NexusCore, so
		 * phase 4 must not ALSO call it -- that would run DriverEntry twice, and the second call
		 * would proxy to the original driver a second time.
		 */
		mLaunched = TRUE;
		mBootBlock->BootFlags |= NXC_BOOTFLAG_ENTRY_HIJACK;
	}
}

VOID
EFIAPI
NexusCoreGetLaunchStats(
	OUT UINT32* OutCalls,
	OUT UINT32* OutRejectedIrql
	)
{
	if (OutCalls != NULL)
		*OutCalls = mLaunchCalls;
	if (OutRejectedIrql != NULL)
		*OutRejectedIrql = mRejectedIrql;
}

VOID
EFIAPI
NexusCoreTryLaunch(
	VOID
	)
{
	/* One-shot, and cheap to re-enter: this runs on EVERY hooked runtime-service call. */
	if (mLaunched || !mArmed || !mBound || mImageBase == NULL || mBootSlotRva == 0)
		return;

	mLaunchCalls++;

	//
	// IRQL gate. On x64 CR8 holds the current IRQL, so this costs one instruction and imports
	// nothing -- which matters because we have no kernel API of our own here.
	//
	// PASSIVE_LEVEL (0) only: NexusCore's stage-1 probes call ExAllocatePool2 and
	// KeDelayExecutionThread, both illegal above PASSIVE, and a wrong assumption here bugchecks
	// instead of reporting. Counted on rejection so a gate that never opens is diagnosable.
	//
	if (__readcr8() != 0)
	{
		mRejectedIrql++;
		return;
	}

	/* Flip BEFORE calling: a reentrant or concurrent runtime call must not double-enter. */
	mLaunched = TRUE;

	//
	// Publish the block pointer into the driver's exported slot. Done HERE, at the last possible
	// moment, rather than during bind: by now phase 3 has run and both mImageBase and mBootBlock hold
	// their FINAL virtual addresses, so there is no ordering dependency to get wrong. Writing it
	// during bind would have stored a physical pointer that phase 3 then invalidated.
	//
	*(UINT64*)(mImageBase + mBootSlotRva) = (UINT64)(UINTN)mBootBlock;

	typedef UINTN (EFIAPI *NXC_DRIVER_ENTRY)(VOID* DriverObject, VOID* RegistryPath);
	CONST NXC_DRIVER_ENTRY Entry = (NXC_DRIVER_ENTRY)(mImageBase + NXC_PAYLOAD_ENTRY_RVA);

	//
	// Called as DriverEntry(NULL, NULL). The payload is built for exactly this -- umap notes mapped
	// drivers "must be designed to function without a real driver object", and NexusCore treats both
	// NULLs as the expected case rather than an error.
	//
	// The return value is deliberately ignored: NexusCore reports through the boot block, which is
	// durable and readable from usermode, whereas a status returned here has nowhere to go.
	//
	(VOID)Entry(NULL, NULL);
}
