/**
 * @file trainer_codegen.cpp
 * @brief Standalone C source-code generation for trainers.
 *
 * Emits a self-contained C source file that implements all cheats
 * defined in a trainer project, including hotkey registration,
 * process attachment, pointer resolution, and value write logic.
 */

#include "trainer_internal.h"

extern "C" {

NEXUS_API NexusResult Nexus_TrainerGenerateSource(
    NexusTrainerHandle trainer,
    const char* outputPath
) {
    if (!trainer || !outputPath) return NEXUS_ERROR_INVALID_PARAMETER;

    TrainerContext* ctx = static_cast<TrainerContext*>(trainer);

    // Create output directory path for main.c
    std::string mainPath = std::string(outputPath) + "\\trainer_main.c";
    std::ofstream ofs(mainPath);
    if (!ofs.is_open()) return NEXUS_ERROR_ACCESS_DENIED;

    // Generate C source code for standalone trainer
    ofs << "/**\n";
    ofs << " * " << ctx->config.name << " Trainer\n";
    ofs << " * Generated by Nexus Engine v0.20.0\n";
    ofs << " * Author: " << ctx->config.author << "\n";
    ofs << " * Version: " << ctx->config.version << "\n";
    ofs << " */\n\n";

    ofs << "#include <windows.h>\n";
    ofs << "#include <stdio.h>\n";
    ofs << "#include <stdint.h>\n\n";

    // Configuration
    ofs << "/* Configuration */\n";
    ofs << "#define TARGET_PROCESS L\"" << ctx->config.targetProcess << "\"\n";
    ofs << "#define TRAINER_NAME \"" << ctx->config.name << "\"\n";
    ofs << "#define NUM_CHEATS " << ctx->cheats.size() << "\n\n";

    // Module list
    ofs << "/* Modules */\n";
    ofs << "const char* g_modules[] = {\n";
    for (size_t i = 0; i < ctx->modules.size(); i++) {
        ofs << "    \"" << ctx->modules[i] << "\"";
        if (i + 1 < ctx->modules.size()) ofs << ",";
        ofs << "\n";
    }
    if (ctx->modules.empty()) ofs << "    NULL\n";
    ofs << "};\n\n";

    // Cheat structures
    ofs << "/* Cheat definitions */\n";
    ofs << "typedef struct {\n";
    ofs << "    const char* name;\n";
    ofs << "    int action;        /* 0=toggle, 1=set, 2=freeze, 3=inc, 4=dec, 5=script */\n";
    ofs << "    UINT vk;\n";
    ofs << "    UINT modifiers;\n";
    ofs << "    int moduleIndex;\n";
    ofs << "    uint64_t offset;\n";
    ofs << "    int64_t pointerOffsets[16];\n";
    ofs << "    int pointerCount;\n";
    ofs << "    int valueType;     /* 0=byte, 1=int16, 2=int32, 3=int64, 4=float, 5=double */\n";
    ofs << "    int64_t setValue;\n";
    ofs << "    int isActive;\n";
    ofs << "} CheatDef;\n\n";

    ofs << "CheatDef g_cheats[NUM_CHEATS] = {\n";
    for (size_t i = 0; i < ctx->cheats.size(); i++) {
        const auto& c = ctx->cheats[i];
        ofs << "    { \"" << EscapeJsonString(c.name) << "\", "
            << static_cast<int>(c.action) << ", "
            << c.hotkey << ", " << c.modifiers << ", "
            << c.moduleIndex << ", 0x" << std::hex << c.offset << std::dec << ", {";

        for (uint32_t j = 0; j < 16; j++) {
            if (j > 0) ofs << ", ";
            if (j < c.pointerCount) {
                ofs << "0x" << std::hex << c.pointerOffsets[j] << std::dec;
            } else {
                ofs << "0";
            }
        }

        ofs << "}, " << c.pointerCount << ", "
            << c.valueType << ", " << c.setValue << ", 0 }";
        if (i + 1 < ctx->cheats.size()) ofs << ",";
        ofs << "\n";
    }
    ofs << "};\n\n";

    // Helper functions
    ofs << "#include <tlhelp32.h>\n";
    ofs << "#include <psapi.h>\n\n";

    ofs << "/* Global state */\n";
    ofs << "HANDLE g_process = NULL;\n";
    ofs << "DWORD g_processId = 0;\n";
    ofs << "uint64_t g_moduleBase[16] = {0};\n";
    ofs << "volatile int g_running = 1;\n\n";

    ofs << "/* Find process by name */\n";
    ofs << "DWORD FindProcessByName(const wchar_t* name) {\n";
    ofs << "    HANDLE snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);\n";
    ofs << "    if (snapshot == INVALID_HANDLE_VALUE) return 0;\n\n";
    ofs << "    PROCESSENTRY32W pe = { sizeof(pe) };\n";
    ofs << "    DWORD pid = 0;\n\n";
    ofs << "    if (Process32FirstW(snapshot, &pe)) {\n";
    ofs << "        do {\n";
    ofs << "            if (_wcsicmp(pe.szExeFile, name) == 0) {\n";
    ofs << "                pid = pe.th32ProcessID;\n";
    ofs << "                break;\n";
    ofs << "            }\n";
    ofs << "        } while (Process32NextW(snapshot, &pe));\n";
    ofs << "    }\n\n";
    ofs << "    CloseHandle(snapshot);\n";
    ofs << "    return pid;\n";
    ofs << "}\n\n";

    ofs << "/* Get module base address */\n";
    ofs << "uint64_t GetModuleBaseAddress(DWORD pid, const char* moduleName) {\n";
    ofs << "    HANDLE snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPMODULE | TH32CS_SNAPMODULE32, pid);\n";
    ofs << "    if (snapshot == INVALID_HANDLE_VALUE) return 0;\n\n";
    ofs << "    MODULEENTRY32 me = { sizeof(me) };\n";
    ofs << "    uint64_t base = 0;\n\n";
    ofs << "    if (Module32First(snapshot, &me)) {\n";
    ofs << "        do {\n";
    ofs << "            if (_stricmp(me.szModule, moduleName) == 0) {\n";
    ofs << "                base = (uint64_t)me.modBaseAddr;\n";
    ofs << "                break;\n";
    ofs << "            }\n";
    ofs << "        } while (Module32Next(snapshot, &me));\n";
    ofs << "    }\n\n";
    ofs << "    CloseHandle(snapshot);\n";
    ofs << "    return base;\n";
    ofs << "}\n\n";

    ofs << "/* Resolve pointer chain */\n";
    ofs << "uint64_t ResolvePointer(uint64_t base, int64_t* offsets, int count) {\n";
    ofs << "    uint64_t addr = base;\n";
    ofs << "    for (int i = 0; i < count; i++) {\n";
    ofs << "        if (!ReadProcessMemory(g_process, (LPCVOID)addr, &addr, 8, NULL)) return 0;\n";
    ofs << "        addr += offsets[i];\n";
    ofs << "    }\n";
    ofs << "    return addr;\n";
    ofs << "}\n\n";

    ofs << "/* Get value size from type */\n";
    ofs << "int GetValueSize(int valueType) {\n";
    ofs << "    switch (valueType) {\n";
    ofs << "        case 0: return 1;  /* byte */\n";
    ofs << "        case 1: return 2;  /* int16 */\n";
    ofs << "        case 2: return 4;  /* int32 */\n";
    ofs << "        case 3: return 8;  /* int64 */\n";
    ofs << "        case 4: return 4;  /* float */\n";
    ofs << "        case 5: return 8;  /* double */\n";
    ofs << "        default: return 4;\n";
    ofs << "    }\n";
    ofs << "}\n\n";

    ofs << "/* Execute a cheat */\n";
    ofs << "void ExecuteCheat(int index) {\n";
    ofs << "    CheatDef* c = &g_cheats[index];\n";
    ofs << "    uint64_t addr = c->moduleIndex >= 0 ? g_moduleBase[c->moduleIndex] + c->offset : c->offset;\n";
    ofs << "    if (c->pointerCount > 0) addr = ResolvePointer(addr, c->pointerOffsets, c->pointerCount);\n";
    ofs << "    if (addr == 0) { printf(\"[ERROR] Failed to resolve address for %s\\n\", c->name); return; }\n\n";
    ofs << "    int size = GetValueSize(c->valueType);\n";
    ofs << "    int64_t currentValue = 0;\n\n";
    ofs << "    switch (c->action) {\n";
    ofs << "        case 0: /* toggle */\n";
    ofs << "            c->isActive = !c->isActive;\n";
    ofs << "            break;\n";
    ofs << "        case 1: /* set */\n";
    ofs << "            WriteProcessMemory(g_process, (LPVOID)addr, &c->setValue, size, NULL);\n";
    ofs << "            break;\n";
    ofs << "        case 2: /* freeze */\n";
    ofs << "            c->isActive = !c->isActive;\n";
    ofs << "            break;\n";
    ofs << "        case 3: /* increment */\n";
    ofs << "            ReadProcessMemory(g_process, (LPCVOID)addr, &currentValue, size, NULL);\n";
    ofs << "            currentValue += c->setValue;\n";
    ofs << "            WriteProcessMemory(g_process, (LPVOID)addr, &currentValue, size, NULL);\n";
    ofs << "            break;\n";
    ofs << "        case 4: /* decrement */\n";
    ofs << "            ReadProcessMemory(g_process, (LPCVOID)addr, &currentValue, size, NULL);\n";
    ofs << "            currentValue -= c->setValue;\n";
    ofs << "            WriteProcessMemory(g_process, (LPVOID)addr, &currentValue, size, NULL);\n";
    ofs << "            break;\n";
    ofs << "    }\n";
    ofs << "    printf(\"[%s] %s\\n\", c->isActive ? \"ON\" : \"OFF\", c->name);\n";
    ofs << "}\n\n";

    ofs << "/* Update frozen values */\n";
    ofs << "void UpdateFrozenValues() {\n";
    ofs << "    for (int i = 0; i < NUM_CHEATS; i++) {\n";
    ofs << "        CheatDef* c = &g_cheats[i];\n";
    ofs << "        if (c->isActive && c->action == 2) { /* freeze */\n";
    ofs << "            uint64_t addr = c->moduleIndex >= 0 ? g_moduleBase[c->moduleIndex] + c->offset : c->offset;\n";
    ofs << "            if (c->pointerCount > 0) addr = ResolvePointer(addr, c->pointerOffsets, c->pointerCount);\n";
    ofs << "            if (addr != 0) {\n";
    ofs << "                int size = GetValueSize(c->valueType);\n";
    ofs << "                WriteProcessMemory(g_process, (LPVOID)addr, &c->setValue, size, NULL);\n";
    ofs << "            }\n";
    ofs << "        }\n";
    ofs << "    }\n";
    ofs << "}\n\n";

    ofs << "/* Console control handler */\n";
    ofs << "BOOL WINAPI ConsoleHandler(DWORD signal) {\n";
    ofs << "    if (signal == CTRL_C_EVENT || signal == CTRL_CLOSE_EVENT) {\n";
    ofs << "        g_running = 0;\n";
    ofs << "        return TRUE;\n";
    ofs << "    }\n";
    ofs << "    return FALSE;\n";
    ofs << "}\n\n";

    ofs << "/* Main entry point */\n";
    ofs << "int main() {\n";
    ofs << "    SetConsoleCtrlHandler(ConsoleHandler, TRUE);\n\n";
    ofs << "    printf(\"========================================\\n\");\n";
    ofs << "    printf(\"  " << ctx->config.name << " Trainer\\n\");\n";
    ofs << "    printf(\"  By " << ctx->config.author << "\\n\");\n";
    ofs << "    printf(\"  Version: " << ctx->config.version << "\\n\");\n";
    ofs << "    printf(\"========================================\\n\\n\");\n\n";

    // Print hotkeys
    ofs << "    printf(\"Hotkeys:\\n\");\n";
    for (const auto& c : ctx->cheats) {
        ofs << "    printf(\"  " << GetHotkeyString(c.hotkey, c.modifiers)
            << " - " << c.name << "\\n\");\n";
    }
    ofs << "    printf(\"  Ctrl+Q - Quit\\n\\n\");\n\n";

    ofs << "    printf(\"Waiting for %ls...\\n\", TARGET_PROCESS);\n\n";

    ofs << "    /* Wait for process */\n";
    ofs << "    while (g_running && g_processId == 0) {\n";
    ofs << "        g_processId = FindProcessByName(TARGET_PROCESS);\n";
    ofs << "        if (g_processId == 0) Sleep(1000);\n";
    ofs << "    }\n\n";

    ofs << "    if (!g_running) return 0;\n\n";

    ofs << "    /* Open process */\n";
    ofs << "    g_process = OpenProcess(PROCESS_ALL_ACCESS, FALSE, g_processId);\n";
    ofs << "    if (g_process == NULL) {\n";
    ofs << "        printf(\"[ERROR] Failed to open process (error %lu)\\n\", GetLastError());\n";
    ofs << "        printf(\"Try running as Administrator.\\n\");\n";
    ofs << "        return 1;\n";
    ofs << "    }\n\n";

    ofs << "    printf(\"[OK] Attached to process (PID: %lu)\\n\", g_processId);\n\n";

    // Get module bases
    ofs << "    /* Get module base addresses */\n";
    for (size_t i = 0; i < ctx->modules.size(); i++) {
        ofs << "    g_moduleBase[" << i << "] = GetModuleBaseAddress(g_processId, g_modules[" << i << "]);\n";
        ofs << "    if (g_moduleBase[" << i << "]) printf(\"[OK] %s @ 0x%llX\\n\", g_modules[" << i << "], g_moduleBase[" << i << "]);\n";
    }
    if (!ctx->modules.empty()) ofs << "    printf(\"\\n\");\n";

    ofs << "\n    printf(\"Trainer ready! Press hotkeys to activate cheats.\\n\\n\");\n\n";

    ofs << "    /* Main loop */\n";
    ofs << "    while (g_running) {\n";
    ofs << "        /* Check if process is still running */\n";
    ofs << "        DWORD exitCode;\n";
    ofs << "        if (!GetExitCodeProcess(g_process, &exitCode) || exitCode != STILL_ACTIVE) {\n";
    ofs << "            printf(\"\\n[!] Process terminated.\\n\");\n";
    ofs << "            break;\n";
    ofs << "        }\n\n";

    ofs << "        /* Check hotkeys */\n";
    for (size_t i = 0; i < ctx->cheats.size(); i++) {
        const auto& c = ctx->cheats[i];
        ofs << "        if (";
        if (c.modifiers & NEXUS_HOTKEY_CTRL) ofs << "(GetAsyncKeyState(VK_CONTROL) & 0x8000) && ";
        if (c.modifiers & NEXUS_HOTKEY_ALT) ofs << "(GetAsyncKeyState(VK_MENU) & 0x8000) && ";
        if (c.modifiers & NEXUS_HOTKEY_SHIFT) ofs << "(GetAsyncKeyState(VK_SHIFT) & 0x8000) && ";
        ofs << "(GetAsyncKeyState(" << c.hotkey << ") & 1)) ExecuteCheat(" << i << ");\n";
    }
    ofs << "        if ((GetAsyncKeyState(VK_CONTROL) & 0x8000) && (GetAsyncKeyState('Q') & 1)) break;\n\n";

    ofs << "        /* Update frozen values */\n";
    ofs << "        UpdateFrozenValues();\n\n";

    ofs << "        Sleep(50); /* ~20 Hz update rate */\n";
    ofs << "    }\n\n";

    ofs << "    /* Cleanup */\n";
    ofs << "    if (g_process) CloseHandle(g_process);\n";
    ofs << "    printf(\"\\nTrainer closed.\\n\");\n";
    ofs << "    return 0;\n";
    ofs << "}\n";

    ofs.close();
    return NEXUS_OK;
}

} // extern "C"
