;
; HookThunk.asm -- the far end of an inline hook. Log the call, then continue as if nothing happened.
;
; ============================================================================================
; STAGE 2. STAGE 1'S DETOUR TOUCHED NO REGISTER; THIS ONE HAS TO PUT BACK EVERYTHING IT TOUCHES.
; ============================================================================================
;
; The per-hook stub generated by Hook.c is two instructions:
;
;       mov  r10, <NXC_HOOK_ENTRY*>         49 BA imm64
;       jmp  qword ptr [rip+0]              FF 25 00000000 + qword(NxcHookThunk)
;
; so the only per-hook value is an immediate, and everything hard lives HERE where it can be read.
; The alternative -- hand-encoding sixty bytes of save/restore per hook in C -- puts the difficult
; part in the place it cannot be reviewed.
;
; ⚠ WHY r10. The Windows x64 ABI makes r10 and r11 volatile, and at a FUNCTION ENTRY neither is
; live: arguments arrive in rcx/rdx/r8/r9 and xmm0-3, and no correct function reads r10 before
; writing it. So the stub can carry a pointer in r10 without disturbing anything the target needs.
; (r10 is also what the syscall stubs use to shadow rcx -- that is inside the stub itself, not at an
; ordinary function entry, and this hook does not target syscall stubs.)
;
; ⚠ WHAT IS SAVED, AND WHY MORE THAN IS STRICTLY NEEDED. At a function entry only rcx, rdx, r8, r9
; and xmm0-3 are live, so those are the minimum. The full volatile set is saved anyway -- rax, r10,
; r11 and xmm4-5 as well -- because "only the argument registers matter" is true of an ENTRY and
; false of any other address, and a future stage that hooks mid-function would inherit a thunk that
; is quietly wrong rather than one that is merely doing slightly more work.
;
; ⚠ STACK ALIGNMENT IS ARITHMETIC, NOT HOPE. rsp is 8 mod 16 at a function entry (the call pushed a
; return address). Seven pushes subtract 56, and (8 - 56) mod 16 = 0, so rsp is 16-aligned before
; the xmm saves -- which is what lets movaps be used instead of movups, and movaps FAULTS rather
; than tolerating a misaligned rsp. That fault is deliberate: it makes an alignment mistake loud.
;
; ⚠ CET IS ACTIVE ON THIS MACHINE (CR4 bit 23) AND THIS IS SHADOW-STACK SAFE BY CONSTRUCTION. The
; one `call` here is matched by the callee's `ret`, so the shadow stack is balanced. The final `jmp`
; is not a call and pushes nothing. The target's own eventual `ret` still finds the return address
; its caller pushed, because this thunk never pushed a competing one.
;

extern NxcHookOnHit : proc

; Byte offset of TrampolineVa within NXC_HOOK_ENTRY. Hook.c C_ASSERTs this, so a field reordering
; is a build break here rather than a jump to a wild address at run time.
NXC_HOOK_TRAMPOLINE_OFFSET equ 16

.code

NxcHookThunk proc

	; ---- save every volatile register -----------------------------------------------------
	push    rax
	push    rcx
	push    rdx
	push    r8
	push    r9
	push    r10
	push    r11                     ; 7 * 8 = 56 -> rsp is now 16-aligned

	sub     rsp, 96
	movaps  xmmword ptr [rsp+00h], xmm0
	movaps  xmmword ptr [rsp+10h], xmm1
	movaps  xmmword ptr [rsp+20h], xmm2
	movaps  xmmword ptr [rsp+30h], xmm3
	movaps  xmmword ptr [rsp+40h], xmm4
	movaps  xmmword ptr [rsp+50h], xmm5

	; ---- NxcHookOnHit(entry, arg1, arg2) --------------------------------------------------
	;
	; The target's first TWO integer arguments go along as EVIDENCE -- opaque qwords, never
	; interpreted, because without the function's prototype nothing else is knowable about them
	; (D6: report evidence, never a verdict).
	;
	; ⚠ TWO, NOT THREE, AND THE REASON IS THE RING. NxcLogRingWrite carries exactly three payload
	; qwords, and the target VA has to be one of them or an entry cannot say what it is about. So
	; three forwarded arguments would mean one of them being accepted here and silently dropped
	; there, which is worse than not collecting it: a reader would have no way to know the record
	; was ever incomplete. Two arrive and two are recorded.
	;
	; Read from the SAVED copies, not the live registers -- rcx is about to become this call's first
	; argument and would otherwise clobber the value being reported.
	;
	; Stack right now, from rsp: 96 bytes of xmm, then the 7 pushes in reverse order
	; (r11, r10, r9, r8, rdx, rcx, rax). So saved rcx is at +96+8*5 and saved rdx at +96+8*4.
	mov     rdx, [rsp+96+8*5]       ; saved rcx  (arg 1 of the target)
	mov     r8,  [rsp+96+8*4]       ; saved rdx  (arg 2 of the target)

	; ⚠ THE RETURN ADDRESS -- WHO CALLED THE TARGET. Added 2026-07-30 after two hardware runs
	; established only that a candidate was NOT the function we wanted. Argument VALUES say what a
	; parameter is; the return address says WHERE WE ARE, and an ntoskrnl RVA can be mapped to its
	; containing function offline with tools this project already has. That turns "wrong again" into
	; a name.
	;
	; ⚠ THE OFFSET IS ARITHMETIC, NOT A GUESS. The stub reached here with `jmp`, never `call`, so it
	; pushed NOTHING -- the only return address on this stack is the one the TARGET's caller pushed.
	; It sat at rsp+0 on entry; we have since pushed 7 registers (56) and subtracted 96, so it is at
	; rsp + 96 + 8*7 = rsp+152. One slot above the saved rax at +144, which is the last of the pushes.
	mov     r9,  [rsp+96+8*7]       ; the TARGET's return address

	; ⚠ ARG3 -- THE TRAP FRAME, and it is the reason execute breakpoints become possible.
	;
	; KiDispatchException(ExceptionRecord, ExceptionFrame, TrapFrame, PreviousMode, FirstChance)
	; puts the trap frame in r8. Resuming an EXECUTE breakpoint needs EFLAGS.RF set in that frame,
	; and the alternative to having the pointer is deriving it -- which nobody can do safely. Windows
	; hands it over; taking it costs one mov from the saved copy.
	;
	; Saved r8 sits at +96+8*3, one slot below the saved rdx already read above. Passed as the FIFTH
	; argument, so it goes on the stack at [rsp+32] AFTER the shadow space is reserved -- the x64 ABI
	; puts arguments 5 and beyond there, immediately past the 32 bytes of home space.
	mov     rax, [rsp+96+8*3]       ; saved r8 (arg 3 of the target -- the TRAP FRAME)

	; ⚠ ARG4 -- ADDED 2026-08-08 FOR B-01/B-02, AND IT IS THE ONE THAT NAMES A PROCESS.
	;
	; NtOpenProcess(OutHandle, Access, ObjectAttributes, CLIENT_ID*) puts the TARGET PID in argument
	; FOUR. Three arguments would have covered NtCreateFile's OBJECT_ATTRIBUTES and stopped one short
	; of "which process is being opened" -- the entire question B-02 exists to answer. Collecting
	; three and calling the item done is the shape
	; [[feedback_a_summary_value_needs_every_path_that_feeds_it_2026_07_30]] warns about: a result fed
	; by a subset of the paths that produce it.
	;
	; Saved r9 sits at +96+8*2, one slot below the saved r8 read just above. It MUST be read BEFORE
	; the `sub rsp, 48` below -- afterwards every offset here is 48 bytes wrong, and the value fetched
	; would be a plausible-looking qword from the middle of the xmm saves.
	;
	; r11 is the scratch: it is volatile, already pushed, and dead until the restores.
	mov     r11, [rsp+96+8*2]       ; saved r9 (arg 4 of the target)

	mov     rcx, r10                ; the NXC_HOOK_ENTRY* the stub put there

	; ⚠ ARG5 GOES AT [rsp+32], PAST THE SHADOW SPACE -- NOT WHEREVER A PUSH LANDS.
	;
	; The first draft did `sub rsp,32` / `push rax` / `sub rsp,8`. That reserves the right TOTAL (48,
	; which keeps the 16-alignment) and puts the value in the WRONG PLACE: after the push it sits at
	; [rsp+8], while the ABI reads argument 5 from [rsp+32]. NxcHookOnHit would have been handed
	; whatever happened to be at +32 as a "trap frame" -- and the next step WRITES to it.
	;
	; 64 = 32 shadow + 8 (arg5) + 8 (arg6) + 8 (arg7) + 8 padding to keep rsp 16-aligned.
	;
	; ⚠ GREW FROM 48 TO 64 WHEN ARG7 ARRIVED, exactly as the previous note predicted: 48 held five
	; and six for free because the sixth landed in padding that already existed, and a SEVENTH forces
	; 56, which is not a multiple of 16. movaps above FAULTS on a misaligned rsp, so getting this
	; wrong is loud rather than subtle -- which is the reason the xmm saves use movaps at all.
	sub     rsp, 64
	mov     qword ptr [rsp+32], rax ; arg5: the TRAP FRAME (== the target's arg3)
	mov     qword ptr [rsp+40], r11 ; arg6: the target's arg4

	; ⚠⚠ ARG7 -- THE TARGET'S ENTRY RSP, AND IT IS WORTH MORE THAN ANY SINGLE ARGUMENT.
	;
	; The x64 ABI passes arguments 1-4 in registers and everything beyond that ON THE STACK, at
	; [entry_rsp + 0x28] onwards (0x20 of shadow space, past the 8-byte return address). Forwarding
	; registers alone therefore caps this hook at four arguments forever -- and the Nt* family needs
	; more than four constantly:
	;
	;   NtSetInformationFile(Handle, Iosb, Info, Length, FileInformationClass)
	;                                                    ^ ARG 5 -- the class, which is the only
	;                                                      thing that says a DELETE is happening
	;   NtCreateFile(..., CreateDisposition, CreateOptions, ...)
	;                                        ^ ARG 9 -- carries FILE_DELETE_ON_CLOSE
	;
	; So rather than adding an eighth, ninth and tenth forwarded argument one at a time -- each a
	; thunk change, each a chance to get an offset wrong -- ONE value is passed and C reads whatever
	; it needs through the residency-checked reader that already exists. The entry rsp is the key to
	; every stack argument at once.
	;
	; ⚠ THE OFFSET IS ARITHMETIC, NOT A GUESS, and it is the SAME 152 the return-address read above
	; uses: 7 pushes (56) plus the 96-byte xmm area. rsp has since moved by the 64 reserved here, so
	; from the CURRENT rsp the target's entry rsp is +64+152 = +216. It is computed AFTER the sub
	; deliberately -- computing it before and holding it would need a register that is not free.
	lea     rax, [rsp+216]
	mov     qword ptr [rsp+48], rax ; arg7: the target's ENTRY RSP -> args 5..N live at +0x28
	call    NxcHookOnHit
	add     rsp, 64

	; ============================================================================================
	; ⚠⚠ THE CLAIM DECISION. rax is 0 to CONTINUE into the target, non-zero to SWALLOW the call.
	; ============================================================================================
	;
	; Claiming means the target NEVER RUNS: we return to ITS caller as if it had returned
	; immediately. For KiDispatchException -- a void function -- that is exactly "this exception was
	; not dispatched", and the trap handler then restores the trap frame and IRETs back to the
	; faulting context. For a DATA breakpoint RIP already points past the access, so execution simply
	; continues. (EXECUTE breakpoints are refused in C, because resuming one without EFLAGS.RF
	; re-enters the same instruction forever -- see NXC_BPD_SLOT::Type.)
	;
	; ⚠ WHY A PLAIN `ret` IS CORRECT HERE, AND WHY IT IS THE ONLY THING THAT IS. The stub reached
	; this thunk with `jmp`, so nothing of ours is on the stack. After the restores below rsp is
	; EXACTLY what it was at the target's first instruction, which means [rsp] is the return address
	; the target's caller pushed. `ret` consumes precisely that.
	;
	; ⚠ AND IT IS SHADOW-STACK CORRECT, WHICH IS NOT OPTIONAL -- CET IS ACTIVE ON THIS MACHINE. The
	; shadow stack holds the address pushed by the CALLER's `call`. Our `ret` pops that same address
	; from the normal stack, so the two agree and the call/ret pair stays balanced. We never pushed a
	; competing return address, which is what makes this safe rather than lucky.
	;
	; ⚠ THE TEST IS HERE, IMMEDIATELY, BECAUSE rax DOES NOT SURVIVE. rax is the first thing pushed
	; and the last thing popped, so the restore sequence below destroys the return value. Branching
	; now is not a style choice.
	;
	; The two epilogues are DUPLICATED rather than shared with a flag register. Every volatile is
	; restored below, so there is nowhere for a flag to live that is not itself being restored --
	; and on the system exception path an explicit second copy is worth more than a clever one.
	test    rax, rax
	jnz     NxcHookThunkClaim

	; ---- put everything back --------------------------------------------------------------
	movaps  xmm0, xmmword ptr [rsp+00h]
	movaps  xmm1, xmmword ptr [rsp+10h]
	movaps  xmm2, xmmword ptr [rsp+20h]
	movaps  xmm3, xmmword ptr [rsp+30h]
	movaps  xmm4, xmmword ptr [rsp+40h]
	movaps  xmm5, xmmword ptr [rsp+50h]
	add     rsp, 96

	pop     r11
	pop     r10

	; The trampoline address is fetched while r10 still holds the context, and LEFT in r10 -- which
	; is legal precisely because r10 is dead at a function entry. Doing it any later would mean
	; restoring r10 and then having nothing to find the trampoline with.
	mov     r10, [r10 + NXC_HOOK_TRAMPOLINE_OFFSET]

	pop     r9
	pop     r8
	pop     rdx
	pop     rcx
	pop     rax

	; Into the trampoline: the stolen instructions, then an absolute jump back to target+N. rsp is
	; exactly what it was on entry, so the target sees its own frame untouched.
	jmp     r10

	; ============================================================================================
	; THE CLAIM EPILOGUE. Identical restores, then `ret` instead of the trampoline jump.
	; ============================================================================================
	;
	; ⚠ THE TRAMPOLINE IS DELIBERATELY NOT LOADED. The continue path does
	; `mov r10, [r10 + NXC_HOOK_TRAMPOLINE_OFFSET]` between popping r11 and r9, because it needs the
	; entry pointer before r10 is overwritten. Here there is nowhere to jump, so r10 is simply
	; restored like every other volatile -- the target is not entered, not even at its stolen bytes.
NxcHookThunkClaim:
	movaps  xmm0, xmmword ptr [rsp+00h]
	movaps  xmm1, xmmword ptr [rsp+10h]
	movaps  xmm2, xmmword ptr [rsp+20h]
	movaps  xmm3, xmmword ptr [rsp+30h]
	movaps  xmm4, xmmword ptr [rsp+40h]
	movaps  xmm5, xmmword ptr [rsp+50h]
	add     rsp, 96

	pop     r11
	pop     r10
	pop     r9
	pop     r8
	pop     rdx
	pop     rcx
	pop     rax

	; rsp is now exactly the target's entry rsp, so [rsp] is its caller's return address.
	; Returning here is indistinguishable, to that caller, from the target having run and returned.
	ret

NxcHookThunk endp

end
