/**
 * @file VisualUefi.c
 * @brief Visual UEFI compatibility shim and library stub implementations
 *
 * When building with the VisualUefi toolchain (Visual Studio + VisualUefi SDK)
 * instead of the standard EDK2 build system, certain library functions and
 * protocol GUIDs that EDK2 auto-generates or links from its library instances
 * must be provided manually. This file contains:
 *
 * - Protocol GUID definitions (NexusBoot, standard EFI protocols, DiskInfo)
 * - Application/driver identification constants (_gUefiDriverRevision, etc.)
 * - Stub implementations for PerformanceLib, DxeServicesLib, HobLib, SortLib
 *
 * The PerformQuickSort stub provides a simple bubble sort fallback for the
 * UefiBootManagerLib's boot option sorting, which normally links SortLib.
 *
 * @note This file is NOT included in EDK2 .inf builds -- only VisualUefi.
 */
#include <Uefi.h>
#include <Pi/PiDxeCis.h>
#include <Protocol/SimpleTextInEx.h>
#include <Protocol/NexusBoot.h>
#include <Library/DebugLib.h>
#include <Library/BaseMemoryLib.h>
#include <Library/MemoryAllocationLib.h>

//
// Application/Driver identification - auto-generated by EDK2 build system
//
CONST UINT32 _gUefiDriverRevision = 0x210;

//
// gEfiCallerBaseName is EMBEDDED IN THE BINARY as a plain ASCII string, so it is readable by
// anything that reads the image off the ESP. It was "NexusBootLoader", which named
// the project in the one place a filename rename cannot reach -- the file's own contents.
// Kept generic and matched to the deploy name (see mDriverPaths in Loader.c).
//
CHAR8 *gEfiCallerBaseName = "PlatformBootMgr";

//
// NexusBoot Driver Protocol GUID
//
EFI_GUID gNexusBootDriverProtocolGuid = EFI_NEXUSBOOT_DRIVER_PROTOCOL_GUID;

//
// Standard EFI Protocol GUIDs
//
EFI_GUID gEfiSimpleTextInputExProtocolGuid = { 0xdd9e7534, 0x7762, 0x4698, { 0x8c, 0x14, 0xf5, 0x85, 0x17, 0xa6, 0x25, 0xaa } };
EFI_GUID gEfiSimpleTextInProtocolGuid = { 0x387477c1, 0x69c7, 0x11d2, { 0x8e, 0x39, 0x0, 0xa0, 0xc9, 0x69, 0x72, 0x3b } };
//  gEfiLegacyBiosProtocolGuid was defined here and never referenced. Removed
// with <Protocol/LegacyBios.h> under the UEFI-only / Windows-11-only decision.
EFI_GUID gEfiBlockIoProtocolGuid = { 0x964e5b21, 0x6459, 0x11d2, { 0x8e, 0x39, 0x0, 0xa0, 0xc9, 0x69, 0x72, 0x3b } };
EFI_GUID gEfiBootLogoProtocolGuid = { 0xcdea2bd3, 0xfc25, 0x4c1c, { 0xb9, 0x7c, 0xb3, 0x11, 0x86, 0x6, 0x49, 0x90 } };
EFI_GUID gEfiFirmwareVolume2ProtocolGuid = { 0x220e73b6, 0x6bdb, 0x4413, { 0x84, 0x5, 0xb9, 0x74, 0xb1, 0x8, 0x61, 0x9a } };
EFI_GUID gEfiLoadFileProtocolGuid = { 0x56EC3091, 0x954C, 0x11d2, { 0x8E, 0x3F, 0x00, 0xA0, 0xC9, 0x69, 0x72, 0x3B } };
EFI_GUID gEfiRamDiskProtocolGuid = { 0xab38a0df, 0x6873, 0x44a9, { 0x87, 0xe6, 0xd4, 0xeb, 0x56, 0x14, 0x84, 0x49 } };
EFI_GUID gEdkiiVariableLockProtocolGuid = { 0xcd3d0a05, 0x9e24, 0x437c, { 0xa8, 0x91, 0x1e, 0xe0, 0x53, 0xdb, 0x76, 0x38 } };
EFI_GUID gEfiDriverHealthProtocolGuid = { 0x2a534210, 0x9280, 0x41d8, { 0xae, 0x79, 0xca, 0xda, 0x1, 0xa2, 0xb1, 0x27 } };
EFI_GUID gEfiDeferredImageLoadProtocolGuid = { 0x15853d7c, 0x3ddf, 0x43e0, { 0xa1, 0xcb, 0xeb, 0xf8, 0x5b, 0x8f, 0x87, 0x2c } };
EFI_GUID gEfiPciRootBridgeIoProtocolGuid = { 0x2f707ebb, 0x4a1a, 0x11d4, { 0x9a, 0x38, 0x00, 0x90, 0x27, 0x3f, 0xc1, 0x4d } };
EFI_GUID gEfiNvmExpressPassThruProtocolGuid = { 0x52c78312, 0x8edc, 0x4233, { 0x98, 0xf2, 0x1a, 0x1a, 0xa5, 0xe3, 0x88, 0xa5 } };
EFI_GUID gEfiTcg2ProtocolGuid = { 0x607f766c, 0x7455, 0x42be, { 0x93, 0x0b, 0xe4, 0xd7, 0x6d, 0xb2, 0x72, 0x0f } };

//
// DiskInfo Protocol GUIDs
//
EFI_GUID gEfiDiskInfoProtocolGuid = { 0xd432a67f, 0x14dc, 0x484b, { 0xb3, 0xbb, 0x3f, 0x2, 0x91, 0x84, 0x93, 0x27 } };
EFI_GUID gEfiDiskInfoAhciInterfaceGuid = { 0x9e498932, 0x4abc, 0x45af, { 0xa3, 0x4d, 0x2, 0x47, 0x78, 0x7b, 0xe7, 0xc6 } };
EFI_GUID gEfiDiskInfoScsiInterfaceGuid = { 0x8f74baa, 0xea36, 0x41d9, { 0x95, 0x21, 0x21, 0xa7, 0xf, 0x87, 0x80, 0xbc } };
EFI_GUID gEfiDiskInfoIdeInterfaceGuid = { 0x5e948fe3, 0x26d3, 0x42b5, { 0xaf, 0x17, 0x61, 0x2, 0x87, 0x18, 0x8d, 0xec } };
EFI_GUID gEfiDiskInfoSdMmcInterfaceGuid = { 0x8deec992, 0xd39c, 0x4a5c, { 0xab, 0x6b, 0x98, 0x6e, 0x14, 0x24, 0x2b, 0x9d } };

//
// Standard EFI GUIDs
//
EFI_GUID gEdkiiStatusCodeDataTypeVariableGuid = { 0xf6ee6dbb, 0xd67f, 0x4ea0, { 0x8b, 0x96, 0x6a, 0x71, 0xb1, 0x9d, 0x84, 0xad } };
EFI_GUID gEfiMemoryTypeInformationGuid = { 0x4c19049f, 0x4137, 0x4dd3, { 0x9c, 0x10, 0x8b, 0x97, 0xa8, 0x3f, 0xfd, 0xfa } };
// gEfiDxeServicesTableGuid now provided by GlueLib
//  gEfiEventLegacyBootGuid was defined here with zero references, same cut as
// gEfiLegacyBiosProtocolGuid above. A legacy-boot event cannot fire on a UEFI-only target.
EFI_GUID gEfiEventReadyToBootGuid = { 0x7ce88fb3, 0x4bd7, 0x4679, { 0x87, 0xa8, 0xa8, 0xd8, 0xde, 0xe5, 0x0d, 0x2b } };

//
// UefiUnload - not needed for applications, stub it out
//
EFI_STATUS
EFIAPI
UefiUnload(
    IN EFI_HANDLE ImageHandle
    )
{
    return EFI_SUCCESS;
}

//
// Performance Library stubs (BasePerformanceLibNull)
//
BOOLEAN
EFIAPI
PerformanceMeasurementEnabled(
    VOID
    )
{
    return FALSE;
}

BOOLEAN
EFIAPI
LogPerformanceMeasurementEnabled(
    IN CONST UINTN Type
    )
{
    return FALSE;
}

EFI_STATUS
EFIAPI
LogPerformanceMeasurement(
    IN CONST VOID *CallerIdentifier OPTIONAL,
    IN CONST VOID *Guid OPTIONAL,
    IN CONST CHAR8 *String OPTIONAL,
    IN UINT64 Address OPTIONAL,
    IN UINT32 Identifier
    )
{
    return EFI_UNSUPPORTED;
}

EFI_STATUS
EFIAPI
StartPerformanceMeasurementEx(
    IN CONST VOID *Handle OPTIONAL,
    IN CONST CHAR8 *Token OPTIONAL,
    IN CONST CHAR8 *Module OPTIONAL,
    IN UINT64 TimeStamp,
    IN UINT32 Identifier
    )
{
    return EFI_UNSUPPORTED;
}

EFI_STATUS
EFIAPI
EndPerformanceMeasurementEx(
    IN CONST VOID *Handle OPTIONAL,
    IN CONST CHAR8 *Token OPTIONAL,
    IN CONST CHAR8 *Module OPTIONAL,
    IN UINT64 TimeStamp,
    IN UINT32 Identifier
    )
{
    return EFI_UNSUPPORTED;
}

//
// DxeServicesLib stubs - these functions are not needed for our boot loader
//
EFI_STATUS
EFIAPI
GetSectionFromFv(
    IN CONST EFI_GUID *NameGuid,
    IN EFI_SECTION_TYPE SectionType,
    IN UINTN SectionInstance,
    OUT VOID **Buffer,
    OUT UINTN *Size
    )
{
    return EFI_NOT_FOUND;
}

EFI_STATUS
EFIAPI
GetFileBufferByFilePath(
    IN BOOLEAN BootPolicy,
    IN CONST EFI_DEVICE_PATH_PROTOCOL *FilePath,
    OUT VOID **FileBuffer,
    OUT UINTN *FileSize
    )
{
    return EFI_NOT_FOUND;
}

//
// HobLib stubs - HOBs are not available in DXE applications
//
EFI_BOOT_MODE
EFIAPI
GetBootModeHob(
    VOID
    )
{
    return BOOT_WITH_FULL_CONFIGURATION;
}

VOID *
EFIAPI
GetFirstGuidHob(
    IN CONST EFI_GUID *Guid
    )
{
    return NULL;
}

//
// SortLib stub
//
VOID
EFIAPI
PerformQuickSort(
    IN OUT VOID *BufferToSort,
    IN CONST UINTN Count,
    IN CONST UINTN ElementSize,
    IN INT32 (EFIAPI *CompareFunction)(IN CONST VOID *Buffer1, IN CONST VOID *Buffer2)
    )
{
    // Simple bubble sort fallback for small arrays (boot options are typically small)
    if (BufferToSort == NULL || Count < 2 || ElementSize == 0 || CompareFunction == NULL) {
        return;
    }

    UINT8 *Base = (UINT8 *)BufferToSort;
    UINT8 TempStack[256];
    VOID *Temp = NULL;

    // For large elements, allocate heap buffer once
    if (ElementSize > sizeof(TempStack)) {
        Temp = AllocatePool(ElementSize);
        if (Temp == NULL) {
            return; // Cannot sort without temp buffer
        }
    } else {
        Temp = TempStack;
    }

    for (UINTN i = 0; i < Count - 1; i++) {
        for (UINTN j = 0; j < Count - i - 1; j++) {
            VOID *Elem1 = Base + (j * ElementSize);
            VOID *Elem2 = Base + ((j + 1) * ElementSize);

            if (CompareFunction(Elem1, Elem2) > 0) {
                CopyMem(Temp, Elem1, ElementSize);
                CopyMem(Elem1, Elem2, ElementSize);
                CopyMem(Elem2, Temp, ElementSize);
            }
        }
    }

    if (Temp != TempStack) {
        FreePool(Temp);
    }
}
